<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("EDIT_CATEGORY"));
   $rows_owner= $this->rows_owner;
   $rows_cus=$this->rows_cus;
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog"]);

dojo.ready(function(){
});

</script>
<form id='add_season' enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
	<div >
		<table  width="100%" style="background:#D6E5F8;">
			<tr>
				<td width="90%" valign="top">
						<fieldset style="border:1px solid #FFF; "><legend align="center" ><strong>EDIT CATEGORY</strong></legend>
						<table>
							<tr>
								<td>Category Name*</td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="required" value="<?php echo $this->rs['category_name'];?>" type="text" name="category_name" id="category_name" class="fullside" /></td>
								<td width="100px">Choose Parent</td>
								<td><select name="category" id="category" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="getOwner();">
									    <option value="-1">No Parent</option>
									   <?php if (!empty($this->category)) foreach($this->category as $row){?>
									    <option value="<?php echo $row['id']?>"<?php if($row['id']==$this->rs['parent']) echo "selected='selected'"?>><?php echo $row['category_name'];?></option>
									    <?php }?>
									</select>
								</td>
								<td width="100px">Status</td>
								<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="getOwner();">
									    <?php if (!empty($this->status)) foreach($this->status as $row){?>
									    <option value="<?php echo $row['key_code']?>"><?php echo $row['name_en']?></option>
									   <?php }?>
									</select>
								</td>
							</tr>
							<tr >
								<td >Description</td>
								<td colspan="5">
										<textarea class="fullside"  dojoType="dijit.form.ValidationTextBox" style="height: 60px !important;"
										tabindex="8" dojoType=""  id="description" name="description" value="<?php echo $this->rs['description'];?>"></textarea>
								</td>
							</tr>
							</table>
							</fieldset>
					
					
			<tr>
				<td colspan="3" align="center" >
					<input dojoType="dijit.form.Button" type="submit" id="btn_save_close" name="btn_save_close" label="Save&Close"  value="submit" >									
					<input dojoType="dijit.form.Button" type="submit" id="btn_save_new" name="save_new" label="Save&New"  value="submit" >									
				</td>
			</tr>
			
		</table>	
	</div>
</form>
