<section class="content">
    <div class="container">
        <div class="inner-page portfolio-container clearfix row">
            <div class="portfolioContainer portfolio_3" id="MixItUp4E1DF6">
            <?php if(!empty($this->rowsphoto))foreach ($this->rowsphoto as $row){?>
                <div class="col-md-4 convertible sports-car mix margin-bottom-50" style="display: inline-block;">
                    <div class="box clearfix"> <a class="fancybox" href="#"><img class="image" src="<?php echo $this->baseUrl()."/slider/".$row['photo_name'];?>" alt=""> </a>
                        <div class="padding-top-25 padding-bottom-10">
                            <h2><?php echo $row['title'];?></h2>
                            </div>
                        <?php echo $row['description'];?>
                    </div>
                </div>
             <?php }?>
               
            </div>
        </div>
    </div>
    <!--container ends--> 
</section>