 <?php 
 	$customer_data = $this->customer_data;
 ?>
 <style>
	.left-side > .left-block > ul{list-style-type: none !important; padding:0 !important}
	.left-side > .left-block > ul > li{padding: 5px 23px !important;}
	.left-side > .left-block > ul > li :BEFORE{border-bottom: 1px solid !important;}
	.left-side > .left-block > ul > li a{color:#C7081B}
</style>
 <div class="clearfix" style="height: 100px"></div>
<section class="content">
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid"> 
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                        <a class="navbar-brand" href="index.html"><span class="logo"><span class="primary_text"><img alt="" src="<?php echo $this->baseUrl();?>/images/customer/no-profile-img.gif" style="width: 50px;"></span> <span class="secondary_text"><?php echo $this->customer_name;?></span></span></a> </div>
                    
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav pull-right" style="margin-top: 24px;">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="#" data-toggle="dropdown">Pages </a></li>
                            <li><a href="#" data-toggle="dropdown">Inventory </a></li>
                            <li><a href="service.html">Services</a></li>
                            <li><a href="our-team.html">Our Team</a></li>
                            <li><a href="#" data-toggle="dropdown">Portfolio</a></li>
                            <li><a href="#" data-toggle="dropdown">Blog </a>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse --> 
                </div>
                <!-- /.container-fluid --> 
            </nav>
        </div>
        <div class="header_shadow"></div>
</section>



<section class="content">
    <div class="container">
        <div class="inner-page row">
            <div class="row">
                <div class="inventory-wide-sidebar-right">
                    <div class=" col-md-9">
                        <div class="car_listings sidebar clearfix">
                            <div class="inventory margin-bottom-10 clearfix scroll_effect fadeIn animated" style="visibility: visible; animation-name: fadeIn;">
								<form action="" method="post">
									
										drfgdrh
								</form>		                        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--container ends--> 
</section>