<!DOCTYPE html>
<html lang="en">
<?php 
     // $base_url = Application_Form_FrmMessage::getUrl("/");
?>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Bootstrap Core CSS -->
   

    <!-- Custom CSS -->
    <link href="<?php echo $this->baseUrl()?>/css/sb-admin-2.css" rel="stylesheet">


    <!-- Custom Fonts -->
    <link href="<?php echo $this->baseUrl()?>/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  
</head>

<body>
    <div id="wrapper">
		<div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header" style="text-align:center;">Welcome to Wedding System</h1>
                </div>
                <!-- /.col-lg-12 -->
                </div>
          
    </div>
</div>

</body>

</html>
