<?php 
	  $url_save = $this->url(array('module'=>'items','controller'=>'index','action'=>'add'));
	  $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
//       $rows_engine=$this->rows_engine;
//       $rows_type=$this->rows_type;
//       $rows_tran=$this->rows_tran;
//       $rows_veh_typ=$this->rows_veh_typ;
?>
<?php $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $this->tr->translate("PRODUCTS").'</title>';
?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<style>
}
.bg{ background:#eeeeee; border:1px solid #000;}
select{ width:100%;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .display_form-add{display:none;}
</style>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.NodeList-manipulate");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: make_store,
    autoComplete: true,                        
    required: true,
    id: "make",
    name: "make",           
    class: 'fullside',            
    onChange: function() {  
    	make_id = dijit.byId('make').get('value');
    	if(make_id==-1){
			dijit.byId('pop_make').show();
	     }
    	else {
    		dijit.byId('model').attr('value','');
    		getallModel(make_id);
    	}           
    }
}, "make");
});
//model controll
dojo.ready(function(){
	addRow();
	}); 

</script>
<form id='add_client' action="<?php echo $url_save; ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<table  width="100%" style="margin-top:10px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Add Item</strong></legend>
							<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
							    
							    <tr>
							    	<td></td>
							    	<td></td>
							    	<td>Product.No.</td>
									<td><input tabindex="1" dojoType="dijit.form.ValidationTextBox" class="fullside" readonly="readonly" id="product_no" name="product_no" value="<?php echo $this->porid ?>" type="text" required="true"></td>
							    </tr>
							    <tr>
									<td>Item Name</td>
									<td><input tabindex="2"dojoType="dijit.form.ValidationTextBox" class="fullside" id="product_name_en" name="product_name_en" value="" type="text" required="true"></td>	
									<td>Category</td>
									<td><input id="make" /></td>
									
<!-- 									<td>Item Name In English</td> -->
<!-- 									<td><input tabindex="3"dojoType="dijit.form.ValidationTextBox" class="fullside" id="product_name_kh" name="product_name_kh" value="" type="text" required="true"></td>	 -->
									
								</tr>
								<tr>
									<td>Measure</td>
									<td>
										<select tabindex="24" name="unit" id="unit" dojoType="dijit.form.FilteringSelect" class="fullside">
										   <?php if(!empty($this->unit)) foreach ($this->unit as $row){?>
										    <option value="<?php echo $row['id'];?>"><?php echo $row['name']?></option>
										    <?php  } ?>
										</select>
									</td>
									<td>Price ($)</td>
									<td><input tabindex="19" dojoType="dijit.form.NumberTextBox" class="fullside" id="price" name="price" value="" type="text"></td>	
								</tr>
								<tr>
									<td>Status</td>
									<td>
									    <select tabindex="24" name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
										    <?php if(!empty($this->status)) foreach($this->status as $row){?>
										    <option value="<?php echo $row['key_code']?>" label="<?php echo $row['name_en'];?>"><?php echo $row['name_en'];?></option>
										    <?php }?>
										</select>
									</td>
									<td>Note:</td>
									<td>
										<textarea class="fullside" name="note"> </textarea>
									</td>
								</tr>
								<tr>
									<td>Item Image 268x327px</td>
									<td valign="middle"><input type="file" name="front" id="front" required="required" class="fullside"/></td>
								</tr>
								<tr>
									<td colspan="4">
										<fieldset>
											<legend>Supplier</legend>
												<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
													<thead>
														<tr>
															<td colspan="8" align="left">
																<input type="button" label="Add Row<?php //echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
															 		iconClass="dijitIconEditProperty" onclick="addRow();" />
																<input type="text" name="identity" id="identity"  value="" >
															 </td>
														</tr>
														<tr>
															<td colspan="8">
																<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
																	<tr id="head-title" class="head-td" align="right"></tr>
																</table>
															</td>
														</tr>
														
													</thead>
											 	</table>
									 	</fieldset>
									</td>
								</tr>
								<tr>
									<td colspan="6" align="center">
									<input type="reset" label="Clear" dojoType="dijit.form.Button" 
										 iconClass="dijitIconClear" /> 
								    <input type="submit" value="SAVE_CLOSE" label="Save&Close" id="save_close" dojoType="dijit.form.Button" name="save_close"
										 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
									<input type="submit" value="SAVE_NEW" label="Save&New" id="save_new" dojoType="dijit.form.Button" name="save_new"
										 iconClass="dijitEditorIcon dijitEditorIconSave"/>
									</td>
								</tr>
								
							</table>
						
		</fieldset>		
		</td>
	</tr>
</table>	
</form>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_make" >
		<form id='frm_make' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>Make Title</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_make" name="txt_make" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="SAVE" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addMake();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Textarea"); 
</script>
<script type="text/javascript">
var url_make = '<?php echo $this->url(array('module'=>'items','controller'=>'index','action'=>'add-make')); ?>';
function addMake(){
	if(dijit.byId('frm_make').validate()){
		dojo.xhrPost({
			url:url_make,
			form: dojo.byId("frm_make"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_make').get('value')
				};			
				addDataToSelectbox(dijit.byId('make'), make_store, Itemmake, data);
				dijit.byId('frm_make').reset();
				dijit.byId("pop_make").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var col = 0;
var no = 0;
var title = 0;
func='';
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th>DEL</th>';
			temp+='<th>N_O</th>';
			temp+='<th>COMPANY_NAME</th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="5%" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="5%" align="center">'+no+'</td>';
			template+='<td><select dojoType="dijit.form.FilteringSelect" id="supplier_name_'+col+'" name="supplier_name_'+col+'" style="width:100%;" placeHolder="Select Supplier">';
				template+='<option value="" label="Select Supplier"></option>';
			<?php foreach($this->supplier as $key){?>
				template+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['company_name'];?></option>';
			<?php }?>
			template+='</td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!='') {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

function hideDialog() {		
	dijit.byId("popup_service").hide();
}
 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		//calculateDiscount(index);
}

</script>