<?php 
	  $url_save = $this->url(array('module'=>'items','controller'=>'index','action'=>'add'));
	  $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
	  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
//       $rows_engine=$this->rows_engine;
//       $rows_type=$this->rows_type;
//       $rows_tran=$this->rows_tran;
//       $rows_veh_typ=$this->rows_veh_typ;
?>
<?php $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $this->tr->translate("PRODUCTS").'</title>';
?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<style>
}
.bg{ background:#eeeeee; border:1px solid #000;}
select{ width:100%;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .display_form-add{display:none;}
</style>

<script type="text/javascript">

dojo.require("dijit.form.Textarea");

dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.NodeList-manipulate");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: make_store,
    autoComplete: true,                        
    required: false,
    id: "make",
    name: "make",           
    class: 'fullside',            
    onChange: function() {  
    	make_id = dijit.byId('make').get('value');
    	if(make_id==-1){
			dijit.byId('pop_make').show();
	     }
    	else { checkItem();
    		//dijit.byId('model').attr('value','');
    		//getallModel(make_id);
    	}           
    }
}, "make");

});
 
//model controll
dojo.ready(function(){
	addRow();
	}); 

</script>
<form id='add_client' action="<?php echo $url_save; ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:10px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong><?php echo $this->tr->translate("ADD_ITEM");?></strong></legend>
							<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
							    
							    <tr>
							    	<td></td>
							    	<td><label name="message" id="message"></label></td>
							    	<td><?php echo $this->tr->translate("ITEM_NO");?></td>
									<td><input tabindex="1" dojoType="dijit.form.ValidationTextBox" class="fullside"  id="product_no" name="product_no" value="<?php echo $this->porid ?>" type="text" required="true"></td>
							    </tr>
							    <tr>
									<td><?php echo $this->tr->translate("ITEM_NAME");?></td>
									<td><input tabindex="2"dojoType="dijit.form.ValidationTextBox" class="fullside" id="product_name_kh" name="product_name_kh" value="" type="text" required="true" onKeyup="checkItem();"></td>	
									<td><?php echo $this->tr->translate("MANAGE_CATEGORY");?></td>
									<td><input id="make" /></td>
									
<!-- 									<td>Item Name In English</td> -->
<!-- 									<td><input tabindex="3"dojoType="dijit.form.ValidationTextBox" class="fullside" id="product_name_kh" name="product_name_kh" value="" type="text" required="true"></td>	 -->
									
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("MANAGE_MEASURE");?></td>
									<td>
										<select tabindex="24" name="unit" id="unit" dojoType="dijit.form.FilteringSelect" class="fullside" onChange="showMeasur();checkItem();">
										    <option>please selected</option>
										   <?php if(!empty($this->unit)) foreach ($this->unit as $row){?>
										    <option value="<?php echo $row['id'];?>"><?php echo $row['name']?></option>
										    <?php  } ?>
										</select>
									</td>
									<td><?php echo $this->tr->translate("PRICE");?> ($)</td>
									<td><input tabindex="19" dojoType="dijit.form.NumberTextBox" class="fullside" id="price" name="price" value="" type="text"></td>	
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("STATUS");?></td>
									<td>
									    <select tabindex="24" name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
										    <?php if(!empty($this->status)) foreach($this->status as $row){?>
										    <option value="<?php echo $row['key_code']?>" label="<?php echo $row['name_en'];?>"><?php echo $row['name_en'];?></option>
										    <?php }?>
										</select>
									</td>
									<td><?php echo $this->tr->translate("NOTE");?></td>
									<td>
										<textarea class="fullside" name="note"> </textarea>
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("IMG");?> 268x327px</td>
									<td valign="middle"><input type="file" name="front" id="front"   class="fullside"/></td>
								</tr>
								<tr>
									<td colspan="4">
										<fieldset>
											<legend><?php echo $this->tr->translate("SUPPLIER");?></legend>
												<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
													<thead>
														<tr>
															<td colspan="8">
																<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
																	<tr id="head-title" class="head-td" align="right"></tr>
																</table>
															</td>
														</tr>
														<tr>
															<td colspan="8" align="left">
																<input type="button" label="<?php echo $this->tr->translate("ADD_SUPPLIER");?>" dojoType="dijit.form.Button" 
															 		iconClass="dijitIconEditProperty" onclick="addRow();" />
																<input type="hidden" name="identity" id="identity"  value="" >
																<input type="hidden" id="sum" name="sum" value="" /> 
																<input type="text" id="sup_id" name="sup_id" value=""/>
																
															 </td>
														</tr>
														
													</thead>
											 	</table>
									 	</fieldset>
									</td>
								</tr>
								<tr>
									<td colspan="6" align="center">
									<input type="reset" label="Clear" dojoType="dijit.form.Button" 
										 iconClass="dijitIconClear" /> 
								    <input type="submit" value="SAVE_CLOSE" label="Save&Close" id="save_close" dojoType="dijit.form.Button" name="save_close"
										 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
									<input type="submit" value="SAVE_NEW" label="Save&New" id="save_new" dojoType="dijit.form.Button" name="save_new"
										 iconClass="dijitEditorIcon dijitEditorIconSave"/>
									</td>
								</tr>
								
							</table>
						
		</fieldset>		
		</td>
	</tr>
</table>	
</form>


<div class="dijitHidden">
 
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_make" >
		<form id='frm_make' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>Make Title</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_make" name="txt_make" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="SAVE" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addMake();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
	
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="show_measure" >
		<form id='show_measure_form' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo  $this->tr->translate("MEASURE_NAME_KH");?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_measure" name="txt_measure" value="" type="text" onKeyup="checkItem();"></td>
				
			</tr>
			<tr>
				<td><?php echo  $this->tr->translate("MEASURE_NAME_EN");?></td>
				<td><input dojoType="dijit.form.ValidationTextBox"  id="txt_measure_en" name="txt_measure_en" value="" type="text"></td>
				
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="SAVE" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addMeasure();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
	
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="popup_supplier" >
		<form id='frm_supplier_info' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onClick">			
			if(this.validate()) {
				return true;
			}else{
				return false;
			}
		</script>
			<table style=" width: 100%">
							<tr>
								<td valign="top" width="34%" style="white-space: nowrap;">
										<fieldset>
											<legend align="left" style="padding-left: 10px;"><strong><?php echo $tr->translate("ADD_SUPPLIER")?></strong></legend>
											<table style="margin: 0 auto;" cellspacing="10">
													<tr>
													   <td><?php echo $tr->translate("SUPPLIER_NAME")?>*</td>
													   <td><input type="text" dojoType="dijit.form.ValidationTextBox" required="required" name="first_name"  id="first_name" value="" class="fullside"></td>
													   <td><?php echo $tr->translate("CUSTOMER_ID")?></td>
													   <td><input type="text" dojoType="dijit.form.TextBox" readonly="readonly" name="su_no"  id="su_no" value="<?php echo $this->su_no;?>" class="fullside"></td>
													</tr>
													<tr>
													   <td><?php echo $tr->translate("SEX")?></td>
													   <td><select dojoType='dijit.form.FilteringSelect' id="title" name="title" class="fullside">
													   			<option value="1"><?php echo $tr->translate("MALE")?></option>
													   			<option value="2"><?php echo $tr->translate("FEMALE")?></option>
													   		</select>
													   	</td>
													   <td></td>
													   <td></td>
													</tr>
													<tr>
														<td><?php echo $tr->translate("Tel")?></td>
														<td><input type="text" dojoType="dijit.form.ValidationTextBox" value=""    id="p_phone" name="p_phone" class="fullside" /></td>
														<td><?php echo $tr->translate("EMAIL")?></td>
														<td><input type="text" dojoType="dijit.form.TextBox" ​ name="p_email"  id="p_email" value="" class="fullside"></td>
														
													</tr>
													<tr>
														<td><?php echo $tr->translate("POSITION")?></td>
														<td><input type="text" dojoType="dijit.form.TextBox"  name="position"  id="position" value="" class="fullside"></td>
														<td><?php echo $tr->translate("STATUS")?></td>
														<td><select dojoType='dijit.form.FilteringSelect' id="statuss" name="statuss" onchange="Showbranch();" class="fullside">
													   			<option value="1">Active</option>
													   			<option value="0">Deactive</option>
													   		</select>
													   	</td>
													</tr>
											</table>
										</fieldset>
								</td>
							</tr>
							<tr>
								<td width="100%" align="top">
										<fieldset><legend align="left" style="padding-left: 10px;"><strong><?php echo $tr->translate("COMPANY_ADDRESS")?></strong></legend>
									   <table style="padding:10px;" cellspacing="10" >
											<tr>
												<td><?php echo $tr->translate("COMPANY_NAME")?></td>
											    <td><input id="company_name" name="company_name" type="text" dojoType="dijit.form.ValidationTextBox" required="required" class="fullside"></td>
												<td title="ទីកន្លែងកំណើត"><?php echo $tr->translate("ADDRESS")?></td>
												<td rowspan="2">
													<textarea class="fullside" tabindex="8" style=" height: 60px !important;"tabindex="21"  id="com_addres" name="com_addres"  ></textarea>
												</td>  
											</tr>
											 
											<tr>
											   <td><?php echo $tr->translate("Tel")?>*</td>
											   <td><input type="text" dojoType="dijit.form.ValidationTextBox" value=""   id="c_phone" name="c_phone" class="fullside" /></td>
											</tr>
											<tr>
											   <td><?php echo $tr->translate("EMAIL")?>*</td>
											   <td><input type="text" dojoType="dijit.form.TextBox" value="" id="c_email" name="c_email" class="fullside" /></td>
											    <td><?php echo $tr->translate("BALANCE")?></td>
											   <td><input type="text" dojoType="dijit.form.TextBox" value="0" required="required"  id="balance" name="balance" class="fullside" /></td>
											</tr>
											 
										</table>
									</fieldset>
								</td>
							</tr>
							<tr align="center">
								<td valign="top">
										 	<input type="button"  label="SAVE" dojoType="dijit.form.Button" 
				 							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addSupplier();"/>
								</td>
							</tr>
					</table>	
			</form>
	</div>
</div>
 

<script type="text/javascript">
dojo.require("dijit.form.Textarea"); 
</script>
<script type="text/javascript">
var url_make = '<?php echo $this->url(array('module'=>'items','controller'=>'index','action'=>'add-make')); ?>';
function addMake(){
	if(dijit.byId('frm_make').validate()){
		dojo.xhrPost({
			url:url_make,
			form: dojo.byId("frm_make"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_make').get('value')
				};			
				addDataToSelectbox(dijit.byId('make'), make_store, Itemmake, data);
				dijit.byId('frm_make').reset();
				dijit.byId("pop_make").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var col = 0;
var no = 0;
var title = 0;
func='';
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $this->tr->translate("DEL");?></th>';
			temp+='<th><?php echo $this->tr->translate("N_O");?></th>';
			temp+='<th><?php echo $this->tr->translate("COMPANY_NAME");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="5%" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="5%" align="center">'+no+'</td>';
			template+='<td><select dojoType="dijit.form.FilteringSelect" id="supplier_name_'+col+'" name="supplier_name_'+col+'" style="width:100%;" placeHolder="Select Supplier" onChange="sumValue('+col+');addSuppliers('+col+');checkItem();" >';
				template+='<option value="" label="Select Supplier">Select Supplier</option>';
			<?php foreach($this->supplier as $key){?>
				template+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name'];?></option>';
			<?php }?>
			template+='</td>';
			 
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!='') {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

function hideDialog() {		
	dijit.byId("popup_service").hide();
}
 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		//calculateDiscount(index);
}
function addSuppliers(i){
	supplier_id=dijit.byId('supplier_name_'+i).get('value');
	if(supplier_id==-1){
		dijit.byId('popup_supplier').show();
		 $('#sup_id').val('');
	}else { 
			 $('#sup_id').val(supplier_id); 
		 }
}
function sumValue(i){
	 $('#sum').attr('value',i);
}

var supplier_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->supplier));?> );
var url_supplier = '<?php echo $this->url(array('module'=>'items','controller'=>'index','action'=>'add-supplier')); ?>';
function addSupplier(){
	ids=$('#sum').val();
	if(dijit.byId('frm_supplier_info').validate()){
		dojo.xhrPost({
			url:url_supplier,
			form: dojo.byId("frm_supplier_info"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
					 	id: data,
					    name: dijit.byId('company_name').get('value')
				 };			
				 addDataToSelectbox(dijit.byId('supplier_name_'+ids), supplier_store, Itemmake, data);
				dijit.byId('frm_supplier_info').reset();
				dijit.byId("popup_supplier").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
//function add measure to table 
function showMeasur(){
	unit=dijit.byId('unit').get('value');
	if(unit==-1){
		dijit.byId('show_measure').show();
	}else {

	}
}
var unit_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->unit));?> );
var url_measur = '<?php echo $this->url(array('module'=>'items','controller'=>'index','action'=>'add-measure')); ?>';
function addMeasure(){
	//ids=$('#sum').val();
	if(dijit.byId('show_measure_form').validate()){
		dojo.xhrPost({
			url:url_measur,
			form: dojo.byId("show_measure_form"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
					 	id: data,
					    name: dijit.byId('txt_measure').get('value')+' '+dijit.byId('txt_measure_en').get('value'),
					     
				 };			
				 addDataToSelectbox(dijit.byId('unit'), unit_store, Itemmake, data);
				dijit.byId('show_measure_form').reset();
				dijit.byId("show_measure").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
//condition name item have already
var url_check_item= '<?php echo $this->url(array('module'=>'items','controller'=>'index','action'=>'get-item')); ?>';
function checkItem(){
	name= dijit.byId('product_name_kh').get('value');
	cat_id= dijit.byId('make').get('value');
	mea_id= dijit.byId('unit').get('value');
	//sup_id= $('#sup_id').val();
	if(name !='' && cat_id !='' && mea_id !=''){
		dojo.xhrPost({
			url: url_check_item,
			content:{
	 			'name':name,
	 			'cat_id':cat_id,
	 			'mea_id':mea_id,
	 			},
			handleAs:"json",
			load: function(data) {
				if(data==1){
	            	   name_kh=dijit.byId('product_name_kh').get('value');
		               dojo.byId('message').innerHTML='<h4  style="color:red;">​'+name_kh+'ឈ្មោះគ្រឿងផ្សំ  មានរួចហើយ!</h4>'; 
		               dijit.byId('product_name_kh').attr('value','');
	               }else {
	            	   dojo.byId('message').innerHTML='';
	               }
			},
			error: function(err) {
				//alert(err);
			}
		});
	}
}

</script>