<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$request=Zend_Controller_Front::getInstance()->getRequest();
echo $this->headTitle($tr->translate("PRODUCTS"));
 $status = $request->getParam('search_status');
 if(empty($status)) $status=-1;
 $make=$request->getParam('make');
 $model=$request->getParam('model');
 $submodel=$request->getParam('submodel');
 $frm =  $this->form_search;
?>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");

var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: make_store,
    autoComplete: true,                        
    required: false,
    id: "make",
    name: "make",    
    placeHolder:"ជ្រើសរើស ប្រភេទគ្រឿងផ្សំ",       
    class: 'fullside',   
    value:'<?php echo $make; ?>',       
    onChange: function() {  
    		make_id=dijit.byId('make').get('value');
    		//alert(make_id);
    		//getallModel(make_id);
    }
}, "make");	

	}); 

</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'items','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
	  <tr> 
		   <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $request->getParam('adv_search');?>" placeholder="<?php echo $tr->translate("SEARCH");?>" type="text" ></td>
		   <td><input id="make" /></td>
		   <td>
		         <td> <?php echo $frm->getElement("status_search");?></td>
		   </td>
		   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	  </tr>
   </table>
   
  
   <?php echo $this->list;?>
</form>
