<?php 
	  $url_save = $this->url(array('module'=>'order','controller'=>'quote','action'=>'add'));
	  //$this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
//       $rows_engine=$this->rows_engine;
//       $rows_type=$this->rows_type;
//       $rows_tran=$this->rows_tran;
//       $rows_veh_typ=$this->rows_veh_typ;
?>
<?php $this->tr = Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $this->tr->translate("PRODUCTS").'</title>';
?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<style>
.bg{ background:#eeeeee; border:1px solid #000;}

select{ width:100%;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .display_form-add{display:none;}
.width {width:76% !important;} 
.l_width{width:20% !important;}
</style>

<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.html");
dojo.require("dojo.parser");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.TimeTextBox");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
//var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
	var arr = ['wedding','breakfast','lunch','dinner'];
		for(i=0;i<arr.length;i++){
			TimeTexbox(arr[i]);
		}
	
});
function TimeTexbox(arr){
	 new dijit.form.TimeTextBox(
		{
		autoComplete: true,                        
		required: true,
		id: "time_"+arr,
		name: "time_"+arr,
		class: 'fullside',
		value: new Date(),
         constraints: {
             timePattern: 'HH:mm',
             clickableIncrement: 'T00:15',
             visibleIncrement: 'T00:15',
             visibleRange: 'T01:00'
         }
     }, "time_"+arr);
	 clickTime(arr);
 }

 function clickTime(arr){
	 dijit.byId("time_"+arr).attr('value','T07:15');
 }
</script>
<form id='add_food' action="<?php echo $url_save; ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:10px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong><?php echo $this->tr->translate("ADD_FOOD");?></strong></legend>
					<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
								<tr>
									<td></td>
									<td></td>
									<td><?php echo $this->tr->translate("QUOTE_NO");?>:</td>
									<td><input type="text" name="qutoe_code" dojoType="dijit.form.ValidationTextBox" class="fullside" readonly="readonly" value="<?php echo $this->quote_id ?>"></td>
								</tr>
							    <tr>
									<td><?php echo $this->tr->translate("CUSTOMER_NAME");?>:</td>
									<td>
										<select  name="customer_name" id="customer_name" onChange="getCustomer(1); getCeremonyDate();" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" placeHolder="Select Customer Name">
										    <option value="" label="<?php echo $this->tr->translate("SELECT_CUSTOMER_NAME");?>"></option>
											<?php if(!empty($this->Customer_name)) foreach($this->Customer_name as $row){?>
										    <option value="<?php echo $row['id']?>" label="<?php echo $row['first_name']." ".$row["last_name"];?>"><?php echo $row['first_name']." ".$row["last_name"];?></option>
										    <?php }?>
										</select>
									</td>
									<td><?php echo $this->tr->translate("CUSTOMER_ID");?>:</td>
									<td>
										<select  name="customer_code" id="customer_code" onChange="getCustomer(2)" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" placeHolder="Select Customer Code">
										   <option value="" label="<?php echo $this->tr->translate("SELECT CUSTOMER_CODE");?>"></option>
										   <?php if(!empty($this->Customer_code)) foreach($this->Customer_code as $row){?>
										    <option value="<?php echo $row['id']?>" label="<?php echo $row['customer_code'];?>"><?php echo $row['customer_code'];?></option>
										    <?php }?>
										</select>
									</td>	
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("Tel");?> :</td>
									<td><input type="text" name="tel" id="tel" dojoType="dijit.form.ValidationTextBox" class="fullside"></td>
									<td><?php echo $this->tr->translate("EMAIL");?> :</td>
									<td><input type="text" name="email" id="email" dojoType="dijit.form.ValidationTextBox" class="fullside" readonly="readonly" value=""></td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("ADDRESS");?> :</td>
									<td><input type="text" name="address" id="address" dojoType="dijit.form.ValidationTextBox" class="fullside"></td>
									<td><?php echo $this->tr->translate("STATUS");?> :</td>
									<td>
									    <select  name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
										    <?php if(!empty($this->status)) foreach($this->status as $row){?>
										    <option value="<?php echo $row['key_code']?>" label="<?php echo $row['name_en'];?>"><?php echo $row['name_en'];?></option>
										    <?php }?>
										</select>
									</td>
								</tr>
					</table>
					<table>
						<tr>
							<td style="background: rgb(206, 238, 255) none repeat scroll 0% 0%;">
								<fieldset>
									<legend><?php echo $this->tr->translate("CEREMONY_DATE");?></legend>
									<table>
										<tr>
											<td><?php echo $this->tr->translate("CEREMONY_DATE");?></td>
											<td><input id="ceremony_date"></td>
											<td><?php echo $this->tr->translate("CEREMONY_ADDRESS");?></td>
											<td><input type="text" name="c_address" id="c_address" dojoType="dijit.form.TextBox"></td>
										</tr>
									</table>
								</fieldset>
							</td>
						</tr>
					</table>
					<div id="mainTabContainer" style="max-width:1110px; height: 540px;" dojoType="dijit.layout.TabContainer" region="center"  >
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("FOOD_FOR_WEDDING");?>">
							<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
								<tr>
									<td><?php echo $this->tr->translate("TITLE");?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" name="title_wedding" value="ម្ហូបសម្រាប់ពិធី"/></td>
									<td colspan="4">
										<table>
											<tr>
												<td>
													<input type="radio" checked="checked" name="is_free_wedding" id="free_qty" value="1" style="line-height: 30px; float: left;"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_BY_QTY");?></span>
													<input style="margin: 0 30px 0 20px; width:32%" value="0" dojoType="dijit.form.NumberTextBox" name="free_wedding" id="free_wedding"> 
												</td>
												<td>
													<input type="radio" name="is_free_wedding" id="free_all_wedding" style="line-height: 30px; float: left;" value="2"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_ALL");?></span>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("QUANTITY");?>:</td>
									<td>
										<input dojoType="dijit.form.NumberTextBox" class="fullside width" id="t_number_wedding" name="t_number_wedding" value="" type="text">
										<select name="label_wedding" id="label_wedding" dojoType="dijit.form.FilteringSelect" required="false" class="fullside l_width" >
											<option value="" label="<?php echo $this->tr->translate("CHOOSE_LABEL");?>"><?php echo $this->tr->translate("CHOOSE_LABEL");?></option>
											<?php foreach ($this->label as $rs_l){?>
													<option value="<?php echo $rs_l["id"];?>"><?php echo $rs_l["name"];?></option>
											<?php }?>
										</select>
									</td>	
									<td><?php echo $this->tr->translate("ALLOCATED_FOOD");?></td>
									<td><input  dojoType="dijit.form.NumberTextBox" class="fullside" id="allocate_number_wedding" name="allocate_number_wedding" value="" type="text"></td>
									<td><?php echo $this->tr->translate("PRICE");?></td>
									<td>
									    <input dojoType="dijit.form.NumberTextBox" class="fullside" id="t_price_wedding" name="t_price_wedding" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("CEREMONY_ADDRESS");?></td>
									<td>
<!-- 										<textarea rows="" cols="" name="address_wedding" id="address_wedding" dojoType="dijit.form.TextBox" class="fullside"></textarea> -->
										<select  name=address_wedding id="address_wedding" dojoType="dijit.form.FilteringSelect" class="fullside" >
 										    <option value="" label="Choose Location"><?php echo $this->tr->translate("CHOOSE_LOCATION");?></option>
										</select>
									</td>
									<td><?php echo $this->tr->translate("CEREMONY_DATE");?></td>
									<td><input type="text" name="date_wedding" id="date_wedding" dojoType="dijit.form.DateTextBox" class="fullside" value="now"></td>
									<td><?php echo $this->tr->translate("CEREMONY_TIME");?>:</td>
									<td><input type="text" name="time_wedding" id="time_wedding" class="fullside"></td>
								</tr>
								<tr>
									
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td><?php echo $this->tr->translate("TOTAL_AMOUNT");?></td>
									<td><input type="text" name="amount_wedding" id="amount_wedding" dojoType="dijit.form.TextBox" class="fullside"></td>
								</tr>
							</table>
							<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
								<thead>
									<tr>
										<td colspan="8" align="left">
											<input type="button" label="<?php echo $this->tr->translate('ADD_FOODS');?>" dojoType="dijit.form.Button" 
										 		iconClass="dijitIconEditProperty" onclick="addRow(1);" />
											<input type="hidden" name="identity_wedding" id="identity_wedding"  value="" >
										 </td>
									</tr>
									<tr>
										<td colspan="8">
											<table id="table_row_wedding" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
												<tr id="head-title-wedding" class="head-td" align="right"></tr>
											</table>
										</td>
									</tr>
									
								</thead>
						 </table>
				</div>
				<div class="tabContentSection" dojoType ="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("FOOD_FOR_BREACKFAST");?>">
					<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
								<tr>
									<td><?php echo $this->tr->translate("TITLE");?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" name="title_breakfast"​ value="អាហារសម្រាប់ពេលព្រឹក"/></td>
									<td colspan="4">
										<table>
											<tr>
												<td>
													<input type="radio" checked="checked" name="is_free_breakfast" id="free_qty_breakfast" value="1" style="line-height: 30px; float: left;"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_BY_QTY");?></span>
													<input style="margin: 0 30px 0 20px; width:32%" value="0" dojoType="dijit.form.NumberTextBox" name="free_breakfast" id="free_breakfast"> 
												</td>
												<td>
													<input type="radio" name="is_free_breakfast" id="free_all_breakfast" style="line-height: 30px; float: left;" value="2"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_ALL");?></span>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("QUANTITY");?>:</td>
									<td>
										<input  dojoType="dijit.form.NumberTextBox" class="fullside width" id="t_number_breakfast" name="t_number_breakfast" value="" type="text">
										<select name="label_breakfast" id="label_breakfast" dojoType="dijit.form.FilteringSelect" required="false" class="fullside l_width" >
											<option value="" label="<?php echo $this->tr->translate("CHOOSE_LABEL");?>"><?php echo $this->tr->translate("CHOOSE_LABEL");?></option>
											<?php foreach ($this->label as $rs_l){?>
													<option value="<?php echo $rs_l["id"];?>"><?php echo $rs_l["name"];?></option>
											<?php }?>
										</select>
									</td>	
									<td><?php echo $this->tr->translate("ALLOCATED_FOOD");?></td>
									<td><input  dojoType="dijit.form.NumberTextBox" class="fullside" id="allocate_number_breakfast" name="allocate_number_breakfast" value="" type="text"></td>
									<td><?php echo $this->tr->translate("PRICE");?></td>
									<td>
									    <input  dojoType="dijit.form.NumberTextBox" class="fullside" id="t_price_breakfast" name="t_price_breakfast" value="" type="text">
									</td>
								</tr>
								
								<tr>
									<td><?php echo $this->tr->translate("CEREMONY_ADDRESS");?></td>
									<td>
<!-- 										<textarea rows="" cols="" name="address_breakfast" id="address_breakfast" dojoType="dijit.form.TextBox" class="fullside"></textarea> -->
										<select  name=address_breakfast id="address_breakfast" dojoType="dijit.form.FilteringSelect" class="fullside" required="false" >
											<option value="" label="Choose Location"><?php echo $this->tr->translate("CHOOSE_LOCATION");?></option>
										</select>
									</td>
									<td><?php echo $this->tr->translate("CEREMONY_DATE");?></td>
									<td><input type="text" name="date_breakfast" id="date_breakfast" dojoType="dijit.form.DateTextBox" class="fullside" value="now"></td>
									<td><?php echo $this->tr->translate("CEREMONY_TIME");?></td>
									<td><input type="text" name="time_breakfast" id="time_breakfast" class="fullside"></td>
								</tr>
								<tr>
									
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td><?php echo $this->tr->translate("TOTAL_AMOUNT");?></td>
									<td><input type="text" name="amount_breakfast" id="amount_breakfast" dojoType="dijit.form.TextBox" class="fullside"></td>
								</tr>
					</table>
					<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $this->tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow(2);" />
									<input type="hidden" name="identity_breakfast" id="identity_breakfast"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row_breakfast" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title-breakfast" class="head-td" align="right"></tr>
									</table>
								</td>
							</tr>
							
						</thead>
				 </table>
				</div>
				<div class="tabContentSection" dojoType ="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("FOOD_FOR_LUNCH");?>">
					<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
								<tr>
									<td><?php echo $this->tr->translate("TITLE");?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" name="title_lunch"​ value="អាហារសម្រាប់ថ្ងៃត្រង់"/></td>
									<!-- <td><?php //echo $this->tr->translate("FREE");?></td> -->
									<td  colspan="4">
										<table>
											<tr>
												<td>
													<input type="radio" checked="checked" name="is_free_lunch" id="free_qty_lunch" value="1" style="line-height: 30px; float: left;"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_BY_QTY");?></span>
													<input style="margin: 0 30px 0 20px; width:32%" value="0" dojoType="dijit.form.NumberTextBox" name="free_lunch" id="free_lunch"> 
												</td>
												<td>
													<input type="radio" name="is_free_lunch" id="free_all_lunch" style="line-height: 30px; float: left;" value="2"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_ALL");?></span>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("QUANTITY");?>:</td>
									<td>
										<input  dojoType="dijit.form.NumberTextBox" class="fullside width" id="t_number_lunch" name="t_number_lunch" value="" type="text">
										<select name="label_lunch" id="label_lunch" dojoType="dijit.form.FilteringSelect" required="false" class="fullside l_width" >
											<option value="" label="<?php echo $this->tr->translate("CHOOSE_LABEL");?>"><?php echo $this->tr->translate("CHOOSE_LABEL");?></option>
											<?php foreach ($this->label as $rs_l){?>
													<option value="<?php echo $rs_l["id"];?>"><?php echo $rs_l["name"];?></option>
											<?php }?>
										</select>
									</td>	
									<td><?php echo $this->tr->translate("ALLOCATED_FOOD");?></td>
									<td><input  dojoType="dijit.form.NumberTextBox" class="fullside" id="allocate_number_lunch" name="allocate_number_lunch" value="" type="text"></td>
									<td><?php echo $this->tr->translate("PRICE");?></td>
									<td>
									    <input  dojoType="dijit.form.NumberTextBox" class="fullside" id="t_price_lunch" name="t_price_lunch" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("CEREMONY_ADDRESS");?></td>
									<td>
<!-- 									<textarea rows="" cols="" name="address_lunch" id="address_lunch" dojoType="dijit.form.TextBox" class="fullside"></textarea> -->
										<select name=address_lunch id="address_lunch" dojoType="dijit.form.FilteringSelect" class="fullside" required="false" >
											<option value="" label="Choose Location"><?php echo $this->tr->translate('CHOOSE_LOCATION');?></option>
										</select>
									</td>
									<td><?php echo $this->tr->translate("CEREMONY_DATE");?></td>
									<td><input type="text" name="date_lunch" id="date_lunch" dojoType="dijit.form.DateTextBox" class="fullside" value="now"></td>
									<td><?php echo $this->tr->translate("CEREMONY_TIME");?></td>
									<td><input type="text" name="time_lunch" id="time_lunch" class="fullside"></td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td><?php echo $this->tr->translate("TOTAL_AMOUNT");?></td>
									<td><input type="text" name="amount_lunch" id="amount_lunch" dojoType="dijit.form.TextBox" class="fullside"></td>
								</tr>
					</table>
					<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $this->tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow(3);" />
									<input type="hidden" name="identity_lunch" id="identity_lunch"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row_lunch" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title-lunch" class="head-td" align="right"></tr>
									</table>
								</td>
							</tr>
							
						</thead>
				 </table>
				</div>
				<div class="tabContentSection" dojoType ="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("FOOD_FOR_DINNER");?>">
					<table style="margin: 0 auto; width:100%; font-size:14px;white-space: nowrap;" cellspacing="5">
								<tr>
									<td><?php echo $this->tr->translate("TITLE");?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" name="title_dinner"​ value="អាហារសម្រាប់ពេលល្ងាច"/></td>
									<td colspan="4">
										<table>
											<tr>
												<td>
													<input type="radio" checked="checked" name="is_free_dinner" id="free_qty_dinner" value="1" style="line-height: 30px; float: left;"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_BY_QTY");?></span>
													<input style="margin: 0 30px 0 20px; width:32%" value="0" dojoType="dijit.form.NumberTextBox" name="free_dinner" id="free_dinner"> 
												</td>
												<td>
													<input type="radio" name="is_free_dinner" id="free_all_dinner" style="line-height: 30px; float: left;" value="2"/>
													<span style="margin-left: 10px"><?php echo $this->tr->translate("FREE_ALL");?></span>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("QUANTITY");?>:</td>
									<td>
										<input  dojoType="dijit.form.NumberTextBox" class="fullside width" id="t_number_dinner" name="t_number_dinner" value="" type="text">
										<select name="label_dinner" id="label_dinner" dojoType="dijit.form.FilteringSelect" required="false" class="fullside l_width" >
											<option value="" label="<?php echo $this->tr->translate("CHOOSE_LABEL");?>"><?php echo $this->tr->translate("CHOOSE_LABEL");?></option>
											<?php foreach ($this->label as $rs_l){?>
													<option value="<?php echo $rs_l["id"];?>"><?php echo $rs_l["name"];?></option>
											<?php }?>
										</select>
									</td>	
									<td><?php echo $this->tr->translate("ALLOCATED_FOOD");?></td>
									<td><input  dojoType="dijit.form.NumberTextBox" class="fullside" id="allocate_number_dinner" name="allocate_number_dinner" value="" type="text"></td>
									<td><?php echo $this->tr->translate("PRICE");?></td>
									<td>
									    <input dojoType="dijit.form.NumberTextBox" class="fullside" id="t_price_dinner" name="t_price_dinner" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $this->tr->translate("CEREMONY_ADDRESS");?></td>
									<td>
<!-- 									<textarea rows="" cols="" name="address_dinner" id="address_dinner" dojoType="dijit.form.TextBox" class="fullside"></textarea> -->
										<select name=address_dinner id="address_dinner" dojoType="dijit.form.FilteringSelect" required="false" class="fullside" >
											<option value="" label="Choose Location"><?php echo $this->tr->translate("CHOOSE_LOCATION");?></option>
										</select>
									</td>
									<td><?php echo $this->tr->translate("CEREMONY_DATE");?></td>
									<td><input type="text" name="date_dinner" id="date_dinner" dojoType="dijit.form.DateTextBox" value="now" class="fullside"></td>
									<td><?php echo $this->tr->translate("CEREMONY_TIME");?></td>
									<td><input type="text" name="time_dinner" id="time_dinner" class="fullside"></td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td><?php echo $this->tr->translate("TOTAL_AMOUNT");?></td>
									<td><input type="text" name="amount_dinner" id="amount_dinner" dojoType="dijit.form.NumberTextBox" class="fullside"></td>
								</tr>
					</table>
					<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $this->tr->translate('ADD_FOODS');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow(4);" />
									<input type="hidden" name="identity_dinner" id="identity_dinner"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row_dinner" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title-dinner" class="head-td" align="right"></tr>
									</table>
								</td>
							</tr>
							
						</thead>
				 </table>
				</div>
				<div class="tabContentSection" dojoType ="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("SACRIFICE_FOOD");?>">
					<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $this->tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRowSacrifice();" />
									<input type="hidden" name="identity_sacrifice" id="identity_sacrifice"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row_sacrifice" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title-sacrifice" class="head-td" align="right"></tr>
									</table>
									<table style="width: 30%; float: right; border:0 !important">
										<tr>
											<td style="border: none;"><?php echo $this->tr->translate('TOTAL');?> :</td>
											<td style="border: none;"><input type="text" name="amount_sacrifice" id="amount_sacrifice" dojoType="dijit.form.NumberTextBox" class="fullside"> </td>
										</tr>
									</table>
								</td>
							</tr>
						</thead>
					</table>
				</div>
				<div class="tabContentSection" dojoType ="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("OTHER_FOOD");?>">
					<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $this->tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRowOther();" />
									<input type="hidden" name="identity_other" id="identity_other"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row_other" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title-other" class="head-td" align="right"></tr>
									</table>
									<table style="width: 30%; float: right; border:0 !important">
										<tr>
											<td style="border: none;"><?php echo $this->tr->translate('TOTAL');?> :</td>
											<td style="border: none;"><input type="text" name="amount_other" id="amount_other" dojoType="dijit.form.NumberTextBox" class="fullside"> </td>
										</tr>
									</table>
								</td>
							</tr>
						</thead>
					</table>
				</div>
				<div class="tabContentSection" dojoType ="dijit.layout.ContentPane" title="<?php echo $this->tr->translate("SERVICES");?>">
					<table id="table_parent" class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $this->tr->translate('ADD_FOODS');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRowService();" />
									<input type="hidden" name="identity_service" id="identity_service"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row_service" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title-service" class="head-td" align="right"></tr>
									</table>
									<table style="width: 30%; float: right; border:0 !important">
										<tr>
											<td style="border: none;"><?php echo $this->tr->translate('TOTAL_AMOUNT');?> :</td>
											<td style="border: none;"><input type="text" name="amount_service" id="amount_service" dojoType="dijit.form.NumberTextBox" class="fullside"> </td>
										</tr>
									</table>
								</td>
							</tr>
						</thead>
				 </table>
				</div>
			</div>		
			<table>
				<tr>
					<td colspan="6" align="center">
						<input type="reset" label="<?php echo $this->tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" /> 
						<input type="submit" value="<?php echo $this->tr->translate('SAVE_CLOSE');?>" label="<?php echo $this->tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close" iconClass="dijitEditorIcon dijitEditorIconSave" /> 
						<input type="submit" value="<?php echo $this->tr->translate('SAVE_NEW');?>" label="<?php echo $this->tr->translate('SAVE_NEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new" iconClass="dijitEditorIcon dijitEditorIconSave"/>
					</td>
				</tr>
			</table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_make" >
		<form id='frm_make' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>Make Title</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_make" name="txt_make" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="SAVE" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addMake();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Textarea"); 
</script>
<script type="text/javascript">
var url_customer = '<?php echo $this->url(array('module'=>'order','controller'=>'quote','action'=>'get-customer-by-id')); ?>';
function getCustomer(type){
	if(type==1){
		var id = dijit.byId('customer_name').get('value');
		dijit.byId('customer_code').attr('value',id);
	}else{
		var id = dijit.byId('customer_code').get('value');
		dijit.byId('customer_name').attr('value',id);
	}
		dojo.xhrPost({
			url: url_customer,
			content:{
	 			'id':id
	 			},
			handleAs:"json",
			load: function(data) {
				//address = "#"+data.house_num+" ,St"+data.street+" "+data.district+" "+data.province;
				dijit.byId('tel').attr('value',data.phone);
				dijit.byId('email').attr('value',data.email);
				dijit.byId('address').attr('value',data.address);
				
			},
			error: function(err) {
				alert(err);
			}
		});
}

var url_item_price = '<?php echo $this->url(array('module'=>'food','controller'=>'index','action'=>'get-item-price')); ?>';
function getItemPrice(index){
	id = dijit.byId('item_name_'+index).get('value');
		dojo.xhrPost({
			url: url_item_price,
			content:{
	 			'id':id
	 			},
			handleAs:"json",
			load: function(data) {
				dijit.byId('price'+index).attr('value',data.price);
				document.getElementById('measure'+index).innerHTML = "/"+data.measure_name_kh;
				dijit.byId('qty'+index).attr('value',1);
				doAmount(index);
			},
			error: function(err) {
				alert(err);
			}
		});
}
var template = '';
var services = '<?php //echo $this->service_options; ?>';

var col_wedding = 0;
var no_wedding = 0;
var title_wedding = 0;

var col_breakfast =0;
var no_breakfast=0;
var title_breakfast = 0;

var col_lunch =0;
var no_lunch =0;
var title_lunch = 0;

var col_dinner =0;
var no_dinner =0;
var title_dinner = 0;

//var title = 0;
func='';
tmp = '';

function addRow(type) { //1 = wedding,2=breakfast,3=lunch,4=dinner 
		if(type==1){
			col_wedding++;
			no_wedding++;
			col = col_wedding;
			no = no_wedding;
			row = "wedding_";
			title = title_wedding;
		}if(type==2){
			col_breakfast++;
			no_breakfast++;
			col = col_breakfast;
			no = no_breakfast;
			row = "breakfast_";
			title = title_breakfast;
		}if(type==3){
			col_lunch++;
			no_lunch++;
			col = col_lunch;
			no = no_lunch;
			row = "lunch_";
			title = title_lunch;
		}if(type==4){
			col_dinner++;
			no_dinner++;
				
			col = col_dinner;
			no = no_dinner;
			row = "dinner_";
			title = title_dinner;
		}
		template='';
		temp='';
			temp+='<th><?php echo $this->tr->translate("DEL");?></th>';
			temp+='<th><?php echo $this->tr->translate("N_O");?></th>';
			temp+='<th><?php echo $this->tr->translate("GATEGORY_FOOD");?></th>';
			temp+='<th><?php echo $this->tr->translate("ITEM_NAME");?></th>';
			//temp+='<th>QTY</th>';
			if(type==1){
				if(title_wedding!=1){
					dojo.query("#head-title-wedding").append(temp);
					title_wedding = 1;
				}
			}
			if(type==2){
				if(title_breakfast!=1){
					dojo.query("#head-title-breakfast").append(temp);
					title_breakfast = 1;
				}
			}
			if(type==3){
				if(title_lunch!=1){
					dojo.query("#head-title-lunch").append(temp);
					title_lunch = 1;
				}
			}
			if(type==4){
				if(title_dinner!=1){
					dojo.query("#head-title-dinner").append(temp);
					title_dinner = 1;
				}
			}
			template+='<td width="3%" align="center"><img onclick="deleteRecord('+"'"+row+"'"+','+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center">'+no+'</td>';
			template+='<td><select dojoType="dijit.form.FilteringSelect" id="food_cat_name_'+row+col+'" onChange="getFoodByCat('+"'"+row+"'"+','+col+')" name="food_cat_name_'+row+col+'" style="width:100%;">';
			template+='<option value="-1"><?php echo $this->tr->translate("SELECT_FOOD_CATEGORY");?></option>';
				<?php foreach($this->food_cat as $key){?>
					template+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name_kh'];?></option>';
				<?php }?>
			template+='</select>';
			template+='<td><select dojoType="dijit.form.FilteringSelect" id="item_name_'+row+col+'" name="item_name_'+row+col+'" style="width:100%;">';
				template+='<option value="-1"><?php echo $this->tr->translate("SELECT_ITEM");?></option>';
			<?php foreach($this->food as $key){?>
				template+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name_kh'];?></option>';
			<?php }?>
			template+='</select>';
			//template+='<td><input type="text" required="true" name="_'+row+col+'" id="qty_'+row+col+'" dojoType="dijit.form.NumberTextBox" placeholder="quantity" style="width: 100%;"/></td>';
			
		tmp='<tr id="row'+row+col+'">';
		tmp+="</tr>";
		if(type==1){
			dojo.query("#table_row_wedding").append(tmp);
			if($("#identity_wedding").val()!='') {
				var identity = $("#identity_wedding").val();
				$("#identity_wedding").val(identity+','+col);
			} else {$("#identity_wedding").val(col);}
		}else if(type==2){
			dojo.query("#table_row_breakfast").append(tmp);
			if($("#identity_breakfast").val()!='') {
				var identity = $("#identity_breakfast").val();
				$("#identity_breakfast").val(identity+','+col);
			} else {$("#identity_breakfast").val(col);}
		}else if(type==3){
			dojo.query("#table_row_lunch").append(tmp);
			if($("#identity_lunch").val()!='') {
				var identity = $("#identity_lunch").val();
				$("#identity_lunch").val(identity+','+col);
			} else {$("#identity_lunch").val(col);}
		}else if(type==4){
			dojo.query("#table_row_dinner").append(tmp);
			if($("#identity_dinner").val()!='') {
				var identity = $("#identity_dinner").val();
				$("#identity_dinner").val(identity+','+col);
			} else {$("#identity_dinner").val(col);}
		}
		dojo.html.set(dojo.byId("row"+row+col),template , {
		     parseContent: true,
		});
 }
no_sa =0;
col_sa =0;
row_sa = "sacrifice_";
title_sacrifice=0;
 function addRowSacrifice(){
	 	template_sa='';
		temp_sa='';
		no_sa++;
		col_sa++;
		temp_sa+='<th><?php echo $this->tr->translate("DEL");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("NO");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("FREE");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("CATEGORY");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("FOOD_NAME");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("QTY");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("PRICE");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("ADDRESS");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("DATE_DO");?></th>';
		temp_sa+='<th><?php echo $this->tr->translate("NOTE");?></th>';
			
		if(title_sacrifice!=1){
		 	dojo.query("#head-title-sacrifice").append(temp_sa);
		 	title_sacrifice = 1;
		}
		template_sa+='<td width="3%" align="center"><img onclick="deleteRecord('+"'"+row_sa+"'"+','+col_sa+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template_sa+='<td align="center">'+no_sa+'</td>';
		template_sa+='<td align="center"><input type="checkbox" name="is_free_'+row_sa+col_sa+'" id="is_free_'+row_sa+col_sa+'" value="1"/></td>';
		template_sa+='<td><select dojoType="dijit.form.FilteringSelect" id="food_cat_name_'+row_sa+col_sa+'" onChange="getFoodByCat('+"'"+row_sa+"'"+','+col_sa+')" name="food_cat_name_'+row_sa+col_sa+'" style="width:100%;">';
		template_sa+='<option value="-1">Select Food Category</option>';
			<?php foreach($this->food_cat as $key){?>
				template_sa+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name_kh'];?></option>';
			<?php }?>
		template_sa+='</select>';
		template_sa+='<td><select dojoType="dijit.form.FilteringSelect" id="item_name_'+row_sa+col_sa+'" name="item_name_'+row_sa+col_sa+'" style="width:100%;">';
			template_sa+='<option value="-1">Select Food</option>';
		<?php foreach($this->food as $key){?>
			template_sa+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name_kh'];?></option>';
		<?php }?>
		template_sa+='</select>';
		template_sa+='<td>';
		template_sa+='<input type="text" style="width:57% !important;" class="width fullside" required="true" onKeyup="doAmountService('+col_sa+');" name="qty_'+row_sa+col_sa+'" id="qty_'+row_sa+col_sa+'" dojoType="dijit.form.NumberTextBox" placeholder="quantity" style="width: 100%;"/>';
		template_sa+='<select style="margin-left: 5px;width:37% !important" name="label_'+row_sa+col_sa+'" id="label_'+row_sa+col_sa+'" dojoType="dijit.form.FilteringSelect" required="false" class="fullside l_width" >';
			template_sa+='<option value="" label="<?php echo $this->tr->translate("CHOOSE_LABEL");?>"><?php echo $this->tr->translate("CHOOSE_LABEL");?></option>';
							<?php foreach ($this->label as $rs_l){?>
								template_sa+='<option value="<?php echo $rs_l["id"];?>"><?php echo $rs_l["name"];?></option>';
							<?php }?>
		template_sa+='</select>';
		template_sa+='</td>';
		template_sa+='<td><input type="text" required="true" onKeyup="doAmountService('+col_sa+');" name="price_'+row_sa+col_sa+'" id="price_'+row_sa+col_sa+'" dojoType="dijit.form.NumberTextBox" placeholder="price" style="width: 100%;"/> <input type="hidden" dojoType="dijit.form.TextBox" id="amount_'+row_sa+col_sa+'" name="amount_'+row_sa+col_sa+'"/></td>';
		template_sa+='<td>';
			template_sa+='<select name="address_'+row_sa+col_sa+'" id="address_'+row_sa+col_sa+'" dojoType="dijit.form.FilteringSelect" required="false" class="fullside" >';
				template_sa+='<option value="" label="Choose Location"><?php echo $this->tr->translate("CHOOSE_LOCATION");?></option>';
			template_sa+='</select>';
		template_sa+='</td>';
		template_sa+='<td>';
			template_sa+='<input type="text" name="date_'+row_sa+col_sa+'" id="date_'+row_sa+col_sa+'" dojoType="dijit.form.DateTextBox" value="now" class="fullside">';
		template_sa+='</td>';
		template_sa+='<td><input type="text"  name="note_'+row_sa+col_sa+'" id="note_'+row_sa+col_sa+'" dojoType="dijit.form.TextBox" placeholder="Note" style="width: 100%;"/></td>';
	 tmp_o='<tr id="row'+row_sa+col_sa+'">';
	 tmp_o+="</tr>";
	 
	 dojo.query("#table_row_sacrifice").append(tmp_o);
	 
		if($("#identity_sacrifice").val()!='') {
			var identity = $("#identity_sacrifice").val();
			$("#identity_sacrifice").val(identity+','+col_sa);
		} else {$("#identity_sacrifice").val(col_sa);}
	 dojo.html.set(dojo.byId("row"+row_sa+col_sa),template_sa , {
	     parseContent: true,
	});
	getAddrOther('sacrifice_',col_sa);
	
 }
no_o =0;
col_o =0;
row_o = "other_";
title_other=0;
 function addRowOther(){
	 	template_o='';
		temp_o='';
		no_o++;
		col_o++;
		temp_o+='<th><?php echo $this->tr->translate("DEL");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("NO");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("FREE");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("CATEGORY");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("FOOD_NAME");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("QTY");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("PRICE");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("ADDRESS");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("DATE_DO");?></th>';
		temp_o+='<th><?php echo $this->tr->translate("NOTE");?></th>';
			
		if(title_other!=1){
		 	dojo.query("#head-title-other").append(temp_o);
		 	title_other = 1;
		}
		template_o+='<td width="3%" align="center"><img onclick="deleteRecord('+"'"+row_s+"'"+','+col_s+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template_o+='<td align="center">'+no_o+'</td>';
		template_o+='<td align="center"><input type="checkbox" name="is_free_'+row_o+col_o+'" id="is_free_'+row_o+col_o+'" value="1"/></td>';
		template_o+='<td><select dojoType="dijit.form.FilteringSelect" id="food_cat_name_'+row_o+col_o+'" onChange="getFoodByCat('+"'"+row_o+"'"+','+col_o+')" name="food_cat_name_'+row_o+col_o+'" style="width:100%;">';
		template_o+='<option value="-1">Select Food Category</option>';
			<?php foreach($this->food_cat as $key){?>
				template_o+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name_kh'];?></option>';
			<?php }?>
		template_o+='</select>';
		template_o+='<td><select dojoType="dijit.form.FilteringSelect" id="item_name_'+row_o+col_o+'" name="item_name_'+row_o+col_o+'" style="width:100%;">';
			template_o+='<option value="-1">Select Food</option>';
		<?php foreach($this->food as $key){?>
			template_o+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['name_kh'];?></option>';
		<?php }?>
		template_o+='</select>';
		template_o+='<td>';
		template_o+='<input type="text" style="width:57% !important;" class="width fullside" required="true" onKeyup="doAmountService('+col_o+');" name="qty_'+row_o+col_o+'" id="qty_'+row_o+col_o+'" dojoType="dijit.form.NumberTextBox" placeholder="quantity" style="width: 100%;"/>';
		template_o+='<select style="margin-left: 5px;width:37% !important" name="label_'+row_o+col_o+'" id="label_'+row_o+col_o+'" dojoType="dijit.form.FilteringSelect" required="false" class="fullside l_width" >';
			template_o+='<option value="" label="<?php echo $this->tr->translate("CHOOSE_LABEL");?>"><?php echo $this->tr->translate("CHOOSE_LABEL");?></option>';
							<?php foreach ($this->label as $rs_l){?>
								template_o+='<option value="<?php echo $rs_l["id"];?>"><?php echo $rs_l["name"];?></option>';
							<?php }?>
		template_o+='</select>';
		template_o+='</td>';
		template_o+='<td><input type="text" required="true" onKeyup="doAmountService('+"'"+row_o+"'"+','+col_o+');" name="price_'+row_o+col_o+'" id="price_'+row_o+col_o+'" dojoType="dijit.form.NumberTextBox" placeholder="price" style="width: 100%;"/> <input type="hidden" dojoType="dijit.form.TextBox" id="amount_'+row_o+col_o+'" name="amount_'+row_o+col_o+'"/></td>';
		template_o+='<td>';
			template_o+='<select name="address_'+row_o+col_o+'" id="address_'+row_o+col_o+'" dojoType="dijit.form.FilteringSelect" required="false" class="fullside" >';
				template_o+='<option value="" label="Choose Location"><?php echo $this->tr->translate("CHOOSE_LOCATION");?></option>';
			template_o+='</select>';
		template_o+='</td>';
		template_o+='<td>';
			template_o+='<input type="text" name="date_'+row_o+col_o+'" id="date_'+row_o+col_o+'" dojoType="dijit.form.DateTextBox" value="now" class="fullside">';
		template_o+='</td>';
		template_o+='<td><input type="text"  name="note_'+row_o+col_o+'" id="note_'+row_o+col_o+'" dojoType="dijit.form.TextBox" placeholder="Note" style="width: 100%;"/></td>';
	 tmp_o='<tr id="row'+row_o+col_o+'">';
	 tmp_o+="</tr>";
	 
	 dojo.query("#table_row_other").append(tmp_o);
	 
		if($("#identity_other").val()!='') {
			var identity = $("#identity_other").val();
			$("#identity_other").val(identity+','+col_o);
		} else {$("#identity_other").val(col_o);}
	 dojo.html.set(dojo.byId("row"+row_o+col_o),template_o , {
	     parseContent: true,
	});
	getAddrOther('other_',col_o);
	
 }
no_s =0;
col_s =0;
row_s = "ser_";
title_service=0;
 function addRowService(){
	 	template_s='';
		temp_s='';
		no_s++;
		col_s++;

		temp_s+='<th><?php echo $this->tr->translate("DEL");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("NO");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("SERVICE_NAME");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("QTY");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("PRICE");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("ADDRESS");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("DATE_DO");?></th>';
		temp_s+='<th><?php echo $this->tr->translate("NOTE");?></th>';
			
		if(title_service!=1){
		 	dojo.query("#head-title-service").append(temp_s);
		 	title_service = 1;
		}
		template_s+='<td width="3%" align="center"><img onclick="deleteRecord('+row_s+','+col_s+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template_s+='<td align="center">'+no_s+'</td>';
		template_s+='<td><select dojoType="dijit.form.FilteringSelect" id="item_name_'+row_s+col_s+'" name="item_name_'+row_s+col_s+'" style="width:100%;">';
		template_s+='<option value="-1">Select Service</option>';
		<?php foreach($this->service as $key){?>
		template_s+='<option value="'+<?php echo $key['id']?>+'"><?php echo $key['title'];?></option>';
		<?php }?>
		template_s+='<td><input type="text" required="true" onKeyup="doAmountService('+col_s+');" name="qty_'+row_s+col_s+'" id="qty_'+row_s+col_s+'" dojoType="dijit.form.NumberTextBox" placeholder="quantity" style="width: 100%;"/></td>';
		template_s+='<td><input type="text" required="true" onKeyup="doAmountService('+col_s+');" name="price_'+row_s+col_s+'" id="price_'+row_s+col_s+'" dojoType="dijit.form.NumberTextBox" placeholder="price" style="width: 100%;"/> <input type="hidden" dojoType="dijit.form.TextBox" id="amount_'+row_s+col_s+'" name="amount_'+row_s+col_s+'"/></td>';
		
		template_s+='<td>';
			template_s+='<select name="address_'+row_s+col_s+'" id="address_'+row_s+col_s+'" dojoType="dijit.form.FilteringSelect" required="false" class="fullside" >';
				template_s+='<option value="" label="Choose Location"><?php echo $this->tr->translate("CHOOSE_LOCATION");?></option>';
			template_s+='</select>';
		template_s+='</td>';
		template_s+='<td>';
			template_s+='<input type="text" name="date_'+row_s+col_s+'" id="date_'+row_s+col_s+'" dojoType="dijit.form.DateTextBox" value="now" class="fullside">';
		template_s+='</td>';
		template_s+='<td><input type="text"  name="note_'+row_s+col_s+'" id="note_'+row_s+col_s+'" dojoType="dijit.form.TextBox" placeholder="Note" style="width: 100%;"/></td>';
	 tmp_s='<tr id="row'+row_s+col_s+'">';
	 tmp_s+="</tr>";
	 dojo.query("#table_row_service").append(tmp_s);
		if($("#identity_service").val()!='') {
			var identity = $("#identity_service").val();
			$("#identity_service").val(identity+','+col_s);
		} else {$("#identity_service").val(col_s);}
	 dojo.html.set(dojo.byId("row"+row_s+col_s),template_s , {
	     parseContent: true,
	});
	getAddrOther('ser_',col_s);
 } 
function hideDialog() {		
	dijit.byId("popup_service").hide();
}
 function deleteRecord(row,index) {
		var identity = $('#identity_'+row).val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity_'+row).val(strings);
		dojo.query("#row"+row+"_"+index).remove();
		//calculateDiscount(index);
}

var url_c_date = '<?php echo $this->url(array('module'=>'order','controller'=>'quote','action'=>'get-ceremony-date'));?>';
 var ceremony_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
  function getCeremonyDate(){
 	 new dijit.form.FilteringSelect({
 		    //store: make_store,
 		    autoComplete: true,                        
 		    required: true,
 		    id: "ceremony_date",
 		    name: "ceremony_date",           
 		    class: 'fullside',  
 		   onChange: function() {  
 	 		   getCAddress();
 	 		 getAddr();
 		   }          
 		    
 		}, "ceremony_date");
 	 
 	 id = dijit.byId('customer_name').get('value');
 	 dojo.xhrPost({
 			url: url_c_date,
 			content:{
 				'id':id
 				},
 			handleAs:"json",
 			load: function(data) {
 				dijit.byId('ceremony_date').reset('value');
 				ceremony_store  = getDataStorefromJSON('id','name', data);
 			    dijit.byId('ceremony_date').set('store',ceremony_store);   

 			},
 			error: function(err) {
 				alert(err);
 			}
 		});
  }
  var url_c_add = '<?php echo $this->url(array('module'=>'order','controller'=>'quote','action'=>'get-address'));?>';
  function getCAddress(){
	  id = dijit.byId('ceremony_date').get('value');
	 	 dojo.xhrPost({
	 			url: url_c_add,
	 			content:{
	 				'id':id
	 				},
	 			handleAs:"json",
	 			load: function(data) {
	 				dijit.byId('c_address').attr('value',data.address_1);
	 				
	 				dijit.byId('date_wedding').attr('value',data.ceremony_date);
// 	 				dijit.byId('address_wedding').attr('value',data.address);

	 				dijit.byId('date_breakfast').attr('value',data.ceremony_date);
// 	 				dijit.byId('address_breakfast').attr('value',data.address);

	 				dijit.byId('date_lunch').attr('value',data.ceremony_date);
// 	 				dijit.byId('address_lunch').attr('value',data.address);

	 				dijit.byId('date_dinner').attr('value',data.ceremony_date);
// 	 				dijit.byId('address_dinner').attr('value',data.address);

	 			},
	 			error: function(err) {
	 				alert(err);
	 			}
	 		});
  }
  var url_addr = '<?php echo $this->url(array('module'=>'order','controller'=>'quote','action'=>'get-all-address'));?>';
  var addr_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
  function getAddr(){
	  id = dijit.byId('ceremony_date').get('value');
	  dojo.xhrPost({
			url: url_addr,
			content:{
				'id':id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				addr_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('address_wedding').reset('value');
			    dijit.byId('address_wedding').set('store',addr_store);

			    dijit.byId('address_breakfast').reset('value');
			    dijit.byId('address_breakfast').set('store',addr_store);

			    dijit.byId('address_lunch').reset('value');
			    dijit.byId('address_lunch').set('store',addr_store);

			    dijit.byId('address_dinner').reset('value');
			    dijit.byId('address_dinner').set('store',addr_store);   
				var arr = data.length;
				for(i=0;i<arr;i++){
					dijit.byId('address_wedding').attr('value',data[0].name);
					dijit.byId('address_breakfast').attr('value',data[0].name);
					dijit.byId('address_lunch').attr('value',data[0].name);
					dijit.byId('address_dinner').attr('value',data[0].name);
				}
			},
			error: function(err) {
				alert(err);
			}
		});
  }
  
  function getAddrOther(row,inx){
	  id = dijit.byId('ceremony_date').get('value');
	  dojo.xhrPost({
			url: url_addr,
			content:{
				'id':id
				},
			handleAs:"json",
			load: function(data) {
				addr_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('address_'+row+inx).reset('value');
			    dijit.byId('address_'+row+inx).set('store',addr_store);
				var arr = data.length;
				for(i=0;i<arr;i++){
					dijit.byId('address_'+row+inx).attr('value',data[0].name);
				}
			},
			error: function(err) {
				alert(err);
			}
		});
  }
  
  var url_food_cat = '<?php echo $this->url(array('module'=>'order','controller'=>'quote','action'=>'get-food-by-cat'));?>';
  var food_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
  function getFoodByCat(row,inx){
	  //alert(row);
	  id = dijit.byId('food_cat_name_'+row+inx).get('value');
	  dojo.xhrPost({
			url: url_food_cat,
			content:{
				'id':id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				food_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('item_name_'+row+inx).reset('value');
			    dijit.byId('item_name_'+row+inx).set('store',food_store);
			},
			error: function(err) {
				alert(err);
			}
		});
  }
  function doAmountService(index){
	  qty = dijit.byId('qty_ser_'+index).get('value');
	  price =dijit.byId('price_ser_'+index).get('value');

	  amount = parseFloat(qty)*parseFloat(price);

	  dijit.byId('amount_ser_'+index).attr('value',amount);
	  doTotal();
  }
  
  function doTotal(){
	  //var identity_service = dijit.byId('identity_service').get('value'); 
	  var identity = $('#identity_service').val();
	  var total = 0;
	  var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			amount = dijit.byId('amount_ser_'+arrays[i]).get('value');
			total = total+parseFloat(amount);
		}
		
		dijit.byId('amount_service').attr('value',total);
  }
</script>