<style>
.cke_contents{ height: 200px !important;}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<title>Add FQAs</title>
<form id='add_faq' action="<?php echo $this->url(array('module'=>'other','controller'=>'faq','action'=>'add')); ?>" enctype="application/x-www-form-urlencoded" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
			return true;
	}else{
			return false;
	}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Add FQAs</strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						
						<tr>
							<td>Question</td>
							<td><textarea class="ckeditor" style="width:96%;min-height:80px;" id="job_purpose" name="faq_question"></textarea></td>
					   </tr>
					   <tr>
							<td>Answer</td>
							<td><textarea class="ckeditor" style="width:96%;min-height:80px;" id="job_requirement" name="faq_answer"></textarea></td>
						</tr>
						<tr>
							<td>Status</td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1">Status</option>
								    <option value="0">Deactive</option>
								</select></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="reset" label="Clear" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" label="Save&Close" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							<input type="submit" value="SAVE_NEW" label="Save&New" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
						   
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea"); 
</script>		