<title>Add Logo</title>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<form id='add_client' action="<?php echo $this->url(array('module'=>'other','controller'=>'photo','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Add Logo</strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
						   <td>Title</td>
						   <td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="title" name="title" value="" type="text"></td>
						</tr>
						<tr>
							<td>Photo Name (248x70px)</td>
							<td><input required="true" class="fullside" id="title" name="photo_name" value="" type="file"></td>
						</tr>
						<tr>
							<td>Status</td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1">Active</option>
								    <option value="0">Deactive</option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="reset" label="Clear" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" label="Save&Close" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							<input type="submit" value="SAVE_NEW" label="Save&New" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>		