<title>Edit Logo</title>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<form id='add_client' action="<?php echo $this->url(array('module'=>'other','controller'=>'photo','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong>Edit Logo</strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td>Title<input id="id" name="id" type="hidden" value="<?php echo $this->row['id'];?>" /></td>
						    <td><input id="old_photo" name="old_photo" type="hidden" value="<?php echo $this->row['photo_name'];?>" />
						   	<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="title" name="title" value="<?php echo $this->row['title'];?>" type="text" /></td>
						</tr>
						
						<tr>
							<td>Photo Name (248x70px)</td>
							<td><input class="fullside" id="title" name="photo_name" value="" type="file">
								<img src="<?php echo $this->baseUrl().'/slider/'.$this->row['photo_name'];?>" style="max-height:40px;"/>
							</td>
						<tr>
						<tr>	
							<td>Status</td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								  <option value="1" <?php if($this->row['status']==1){echo'selected="selected"';}?> >Active</option>
								  <option value="0" <?php if($this->row['status']==0){echo'selected="selected"';}?>>Deactive</option>
								 </select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="reset" label="Clear" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							<input type="submit" value="SAVE_NEW" label="Edit" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>		