<?php
$this->headTitle('User change password page'); 
echo $this->headTitle();
$link = $this->url;
?>

<form action="<?php echo $this->url(array('module'=>'','controller'=>'customer','action'=>'forgetpassword')); ?>" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 10px auto; width: 480px">
		<tr>
			<td>
				<fieldset>
					<legend><strong>Forget Password</strong></legend>
					<table cellspacing="20" width="100%">
						<tr>
							<td align="center" valign="top">
								<?php if(empty($link)){?>
								<table width="100%">
									<tr>
										<td>E-mail Address:</td>							
										<td>
											<input style="width:100%" id="email" name="email" value="" type="email" class="form-control">
										</td>
									</tr>
								</table>
								<?php }else {?>
								<table width="100%">
									<tr>
										<td>New Password: <span style="color:#66cc66;"> &nbsp;(Password length between 6 - 8 characters)</span></td>							
										<td>
											<input style="width:100%" id="new_password" name="new_password" type="password" pattern=".{6,}" required maxlength="8" title="Password at least 6 characters and maximum 8 characters!" class="form-control">
										</td>
									</tr>
								</table>
								<?php }?>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="right">
				<input class="button"  type="submit" value="send" label="Send" id="submitButton"/> 							
			</td>
		</tr>
	</table>
	
			
</form>