<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage(); 
$froms = $this->frmbooking;	  
?>
<!--Header Start-->

<!--Header End-->
<style>
	dt{ display: none;}
</style>
<style>
		#calendar,
		#calendar2,
		#calendar3 {
			border: 1px solid #DDD;
			font-family: Tahoma;
			font-size: 12px;
			-webkit-border-radius: 5px;
			-moz-border-radius: 5px;
			border-radius: 5px;
		}
		.my-dropdown input{ 
		padding: 5px;
	-webkit-border-radius: 5px;
-moz-border-radius: 5px;
border-radius: 5px;
}
</style>
<script>
	var myCalendar;
	function doOnLoad() {
		myCalendar = new dhtmlXCalendarObject(["calendar","calendar2","calendar3",]);
	}
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/codebase/dhtmlxcalendar.css"/>
<script src="<?php echo $this->baseUrl()?>/codebase/dhtmlxcalendar.js"></script>
<section class="message-wrap">
    <div class="container">
        <div class="row">
            <h2 class="col-lg-9 col-md-8 col-sm-12 col-xs-12 xs-padding-left-15">Discover a website for car dealers that converts visitors to <span class="alternate-font">customers</span></h2>
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 xs-padding-right-15"> <a href="#" class="default-btn pull-right action_button lg-button">Schedule a Test Drive</a> </div>
        </div>
    </div>
    <div class="message-shadow"></div>
</section>
<!--message-wrap ends-->
<section class="content">
    <div class="container">
        <div class="homepage margin-bottom-none">
        <section class="welcome-wrap padding-top-30 sm-horizontal-15">
<div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 welcome padding-left-none padding-bottom-40 scroll_effect fadeInUp">
                        <h4 class="margin-bottom-25 margin-top-none"><strong>WELCOME</strong><span style="text-transform: uppercase;"><?php echo $this->welcome['title'];?></span></h4>
                        <?php echo $this->welcome['description'];?>
                    </div>
                    <!--welcome ends-->
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 padding-right-none sm-padding-left-none md-padding-left-15 xs-padding-left-none padding-bottom-40 scroll_effect fadeInUp" data-wow-delay='.2s' style="z-index:100">
                        <h4 class="margin-bottom-25 margin-top-none"><strong>SEARCH</strong> CAR RENTAL BOOKING</h4>
                        <div class="search-form margin-top-20 padding-vertical-20">
                            <form method="post">
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Pickup Date
                                            <input type="text" name="pickup_date" value="<?php echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                        Pickup Time
                                            <input type="text" name="pickup_time" value="<?php echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                     <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        Return Date
                                            <input type="text" name="return_date" value="<?php echo date("d-m-Y");?>" id="calendar2" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                        Return Time
                                            <input type="text" name="return_time" value="<?php echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
                                        </div>
                                    </div>
                                </div>
                                 <div class="select-wrapper clearfix">
                                     <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="my-dropdown make-dropdown">
                                         <div class="form-element" style="float:right;">
	                                        <input type="submit" name="search_vehicle" value="Find Vehicle Now" class="find_new_vehicle pull-right md-button">
	                                    </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </form>
                        </div>
                    </div>
                    <!--invetory ends--> 
                </div>
</section>
            <section class="car-block-wrap">
                <div class="container">
                    <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <ul id="myTab" class="nav nav-tabs">
                            <li class="active"><a href="#vehicle" data-toggle="tab"><?php echo $tr->translate("Search Car Rental Booking");?></a></li>
                            <li><a href="#features" data-toggle="tab"><?php echo $tr->translate("Search City Tur Booking");?></a></li>
                            <li><a href="#technical" data-toggle="tab"><?php echo $tr->translate("Search Taxi Booking");?></a></li>
                        </ul>
                        <div id="myTabContent" class="tab-content margin-top-15 margin-bottom-20">
                            <div class="tab-pane fade in active" id="vehicle">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding-right-none sm-padding-left-none md-padding-left-15 xs-padding-left-none padding-bottom-40 scroll_effect fadeInUp" data-wow-delay='.2s' style="z-index:100">
			                        <h5 class="margin-bottom-25 margin-top-none" style="color: #F00;"><?php //echo $tr->translate("RENT_A_CAR_FOR_SELF_DRIVE_OR_WITH_DRIVER");?></h5>
			                        <div class="search-form margin-top-20 padding-vertical-20">
			                            <form method="post" action="#">
<!-- 			                                <div class="select-wrapper clearfix"> -->
<!-- 			                                    <div class="min-price">
			                                        	<span class="col-md-3 "><?php //echo $tr->translate("Pickup Date");?></span>
<!-- 			                                            <div class="col-md-4"> -->
<!-- 			                                            	<div class="my-dropdown make-dropdown"> -->
			                                                	<input type="text" value="<?php //echo date("d-m-Y");?>" id="calendar" style="width: 100% !important;padding:1px !important;" >
<!-- 			                                                </div> -->
<!-- 			                                            </div> 
			                                            <span class="col-md-3"><?php echo $tr->translate("Return Date");?></span>
<!-- 			                                            <div class="col-md-4"> -->
<!-- 			                                            <div class="my-dropdown make-dropdown"> 
			                                               <input type="text" value="<?php //echo date("d-m-Y");?>" id="calendar2"  style="width: 100% !important; padding:1px !important;" />
<!-- 			                                            </div> -->
<!-- 			                                        </div> -->
<!-- 			                                    </div> -->
<!-- 			                                    <div class="min-price"> -->
			                                        	<span class="col-md-3"><?php //echo $tr->translate("Pickup Time");?></span>
<!-- 			                                            <div class="col-md-4"> -->
<!-- 			                                            	<div class="my-dropdown make-dropdown"> -->
			                                                	<?php //echo $froms->getElement('ptime');?>
<!-- 			                                                </div> -->
<!-- 			                                            </div> -->
			                                            <span class="col-md-3"><?php //echo $tr->translate("Return Time");?></span>
<!-- 			                                            <div class="col-md-4"> -->
<!-- 			                                            <div class="my-dropdown make-dropdown"> -->
			                                                <?php //echo $froms->getElement('retime');?>
<!-- 			                                            </div> -->
<!-- 			                                        </div> -->
<!-- 			                                    </div> -->
<!-- 			                                     <div class="min-price"> -->
<!-- 			                                        	<span class="col-md-2 "></span> -->
<!-- 			                                            <div class="col-md-4"> -->
<!-- 			                                            	<div class="my-dropdown make-dropdown"> -->
			                                                	
<!-- 			                                                </div> -->
<!-- 			                                            </div> -->
<!-- 			                                            <span class="col-md-2"></span> -->
<!-- 			                                            <div class="col-md-4"> -->
<!-- 			                                            <div class="my-dropdown make-dropdown"> -->
<!-- 			                                                <input type="button" value="Continue" /> -->
<!-- 			                                            </div> -->
<!-- 			                                        </div> -->
<!-- 			                                    </div> -->
<!-- 			                                	<div class="min-price"> -->
<!-- 				                                	<div><hr /></div> -->
<!-- 				                                </div> -->
<!-- 			                                </div> -->
			                            </form>
			                        </div>
			                    </div>
			                    <!--invetory ends--> 
                            </div>
                            <div class="tab-pane fade" id="features">
                                <ul class="fa-ul">
                                    <li><i class="fa-li fa fa-check"></i> Wind Deflector</li>
                                </ul>
                            </div>
                            <div class="tab-pane fade" id="technical">
                                <table class="technical">
                                    <thead>
                                        <tr>
                                            <th>Engine</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Compression ratio</td>
                                            <td>12.5 : 1</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" id="location">
                                <div id='google-map-listing' class="contact" data-longitude='-79.38' data-latitude='43.65' data-zoom='11' style="height: 350px;" data-parallax="false"></div>
                            </div>
                            <div class="tab-pane fade" id="comments">
                                <p>Vestibulum sit amet ligula eget nibh cursus bibendum et id eros. Nam congue, dui quis consectetur blandit, neque neque mattis diam, 
                                    vitae egestas urna lectus eu turpis. In vitae commodo sem. Etiam vehicula sed ligula malesuada cursus. Cras augue elit, tempus at dignissim 
                                    sed, egestas eget leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam mollis luctus nibh et 
                                    bibendum. Morbi congue lectus nec congue congue. Nulla molestie feugiat quam ac sollicitudin. Nulla sed congue lectus. Donec blandit elit 
                                    sit amet aliquet laoreet.</p>
                                <p><img src="http://demo.themesuite.com/automotive/images/engine.png" alt="engine" /></p>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <!--welcome ends-->
                    
                    
                    
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 margin-bottom-none">
                            <div class="flip margin-bottom-30">
                                <div class="card">
                                    <div class="face front"><img class="img-responsive" src="http://demo.themesuite.com/automotive/images/car1.jpg" alt=""></div>
                                    <div class="face back">
                                        <div class='hover_title'>Race Ready</div>
                                        <a href="inventory-listing.html"><i class="fa fa-link button_icon"></i></a> <a href="images/car1-lrg.jpg" class="fancybox"><i class="fa fa-arrows-alt button_icon"></i></a> </div>
                                </div>
                            </div>
                            <h4><a href="#">FACTORY READY FOR TRACK DAY</a></h4>
                            <p class="margin-bottom-none">Sea veniam lucilius neglegentur ad, an per sumo volum
                                voluptatibus. Qui cu everti repudiare. Eam ut cibo nobis 
                                aperiam, elit qualisque at cum. Possit antiopam id est. 
                                Illud delicata ea mel, sed novum mucius id. Nullam qua.</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 margin-bottom-none">
                            <div class="flip horizontal margin-bottom-30">
                                <div class="card">
                                    <div class="face front"><img class="img-responsive" src="http://demo.themesuite.com/automotive/images/car2.jpg" alt=""></div>
                                    <div class="face back">
                                        <div class='hover_title'>Family Oriented</div>
                                        <a href="inventory-listing.html"><i class="fa fa-link button_icon"></i></a> <a href="images/car2-lrg.jpg" class="fancybox"><i class="fa fa-arrows-alt button_icon"></i></a> </div>
                                </div>
                            </div>
                            <h4><a href="#">A SPORT UTILITY FOR THE FAMILY</a></h4>
                            <p class="margin-bottom-none">Cum ut tractatos imperdiet, no tamquam facilisi qui. 
                                Eum tibique consectetuer in, an legimus referrentur vis, 
                                vocent deseruisse ex mel. Sed te idque graecis. Vel ne 
                                libris dolores, in mel graece dolorum.</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 margin-bottom-none">
                            <div class="flip margin-bottom-30">
                                <div class="card">
                                    <div class="face front"><img class="img-responsive" src="http://demo.themesuite.com/automotive/images/car3.jpg" alt=""></div>
                                    <div class="face back">
                                        <div class='hover_title'>World Class</div>
                                        <a href="inventory-listing.html"><i class="fa fa-link button_icon"></i></a> <a href="images/car3-lrg.jpg" class="fancybox"><i class="fa fa-arrows-alt button_icon"></i></a> </div>
                                </div>
                            </div>
                            <h4><a href="#">MAKE AN EXECUTIVE STATEMENT</a></h4>
                            <p class="margin-bottom-none">Te inermis cotidieque cum, sed ea utroque atomorum 
                                sadipscing. Qui id oratio everti scaevola, vim ea augue 
                                ponderum vituperatoribus, quo adhuc abhorreant 
                                omittantur ad. No his fierent perpetua consequat, et nis.</p>
                        </div>
                    </div>
                </div>
            </section>
            
            <!--car-block-wrap ends-->
            <div class="row parallax_parent design_2 margin-bottom-40 margin-top-30">
                <div class="parallax_scroll clearfix" data-velocity="-.5" data-offset="-200" data-image="http://demo.themesuite.com/automotive/images/parallax1.jpg">
                    <div class="overlay">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 padding-left-none xs-margin-bottom-none xs-padding-top-30 scroll_effect bounceInLeft"> <span class="align-center"><i class="fa fa-6x fa-bar-chart-o"></i></span>
                                    <h3>Results Driven</h3>
                                    <p>Sed ut perspiciatis unde om nis
                                        natus error sit volup atem accusant 
                                        dolorem que laudantium. Totam 
                                        aperiam, eaque ipsa quae ai.</p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 xs-margin-bottom-none xs-padding-top-30 scroll_effect bounceInLeft" data-wow-delay=".2s"> <span class="align-center"><i class="fa fa-6x fa-road"></i></span>
                                    <h3>Proven Technology</h3>
                                    <p>Sed ut perspiciatis unde om nis
                                        natus error sit volup atem accusant 
                                        dolorem que laudantium. Totam 
                                        aperiam, eaque ipsa quae ai.</p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 xs-margin-bottom-none xs-padding-top-30 scroll_effect bounceInRight" data-wow-delay=".2s"> <span class="align-center"><i class="fa fa-6x fa-flag-checkered"></i></span>
                                    <h3>Winning Culture</h3>
                                    <p>Sed ut perspiciatis unde om nis
                                        natus error sit volup atem accusant 
                                        dolorem que laudantium. Totam 
                                        aperiam, eaque ipsa quae ai.</p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 xs-margin-bottom-none xs-padding-top-30 padding-right-none scroll_effect bounceInRight"> <span class="align-center"><i class="fa fa-6x fa-dashboard"></i></span>
                                    <h3>Top Performance</h3>
                                    <p>Sed ut perspiciatis unde om nis
                                        natus error sit volup atem accusant 
                                        dolorem que laudantium. Totam 
                                        aperiam, eaque ipsa quae ai.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--car-info-wrap ends-->
            <section class="welcome-wrap padding-top-30 sm-horizontal-15">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 welcome padding-left-none padding-bottom-40 scroll_effect fadeInUp">
                        <h4 class="margin-bottom-25 margin-top-none"><strong>WELCOME</strong> TO YOUR NEW WEBSITE</h4>
                        <p>Lorem ipsum dolor sit amet, falli tollit cetero te eos. Ea ullum liber aperiri mi, impetus
                            ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft 
                            philosophia, malis necessitatibus no mei. Volumus sensibus qui ex, eum duis doming 
                            ad. Modo liberavisse eu mel, no viris prompta sit. Pro labore sadipscing et. Ne peax
                            egat usu te mel <span class="alternate-font">vivendo scriptorem</span>. Pro labore sadipscing et. Ne pertinax egat usu te 
                            mel vivendo scriptorem.</p>
                        <p>Cum ut tractatos imperdiet, no tamquam facilisi qui. Eum tibique consectetuer in, an 
                            referrentur vis, vocent deseruisse ex mel. Sed te <span class="alternate-font">idque graecis</span>. Vel ne libris dolores, 
                            mel graece mel vivendo scriptorem dolorum.</p>
                    </div>
                    <!--welcome ends-->
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 padding-right-none sm-padding-left-none md-padding-left-15 xs-padding-left-none padding-bottom-40 scroll_effect fadeInUp" data-wow-delay='.2s' style="z-index:100">
                        <h4 class="margin-bottom-25 margin-top-none"><strong>SEARCH</strong> OUR INVENTORY</h4>
                        <div class="search-form margin-top-20 padding-vertical-20">
                            <form method="post" action="#">
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="min-price select-dropdown">
                                            <div class="my-dropdown min-price-dropdown min-dropdown">
                                                <select name="min-year" class="css-dropdowns" tabindex="1" >
                                                    <option value="">Min Year</option>
                                                    <option>2015</option>
                                                    <option>2014</option>
                                                    <option>2013</option>
                                                    <option>2012</option>
                                                    <option>2011</option>
                                                    <option>2010</option>
                                                    <option>2009</option>
                                                    <option>2008</option>
                                                    <option>2007</option>
                                                    <option>2006</option>
                                                    <option>2005</option>
                                                    <option>2004</option>
                                                </select>
                                            </div>
                                            <span class="my-dropdown">to</span>
                                            <div class="my-dropdown max-price-dropdown min-dropdown">
                                                <select name="max-year" class="css-dropdowns" tabindex="1" >
                                                    <option value="">Max Year</option>
                                                    <option>2015</option>
                                                    <option>2014</option>
                                                    <option>2013</option>
                                                    <option>2012</option>
                                                    <option>2011</option>
                                                    <option>2010</option>
                                                    <option>2009</option>
                                                    <option>2008</option>
                                                    <option>2007</option>
                                                    <option>2006</option>
                                                    <option>2005</option>
                                                    <option>2004</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="min-price select-dropdown">
                                            <div class="my-dropdown min-price-dropdown min-dropdown">
                                                <select name="min-price" class="css-dropdowns" tabindex="1" >
                                                    <option value="">Min Price</option>
                                                    <option>0</option>
                                                    <option>&lt; 10,000</option>
                                                    <option>&lt; 20,000</option>
                                                    <option>&lt; 30,000</option>
                                                    <option>&lt; 40,000</option>
                                                    <option>&lt; 50,000</option>
                                                    <option>&lt; 60,000</option>
                                                    <option>&lt; 70,000</option>
                                                    <option>&lt; 80,000</option>
                                                    <option>&lt; 90,000</option>
                                                    <option>&lt; 100,000</option>
                                                    <option>&lt; 120,000</option>
                                                    <option>&lt; 150,000</option>
                                                </select>
                                            </div>
                                            <span class="my-dropdown">to</span>
                                            <div class="my-dropdown max-price-dropdown min-dropdown">
                                                <select name="max-price" class="css-dropdowns" tabindex="1" >
                                                    <option value="">Max Price</option>
                                                    <option>0</option>
                                                    <option>&lt; 10,000</option>
                                                    <option>&lt; 20,000</option>
                                                    <option>&lt; 30,000</option>
                                                    <option>&lt; 40,000</option>
                                                    <option>&lt; 50,000</option>
                                                    <option>&lt; 60,000</option>
                                                    <option>&lt; 70,000</option>
                                                    <option>&lt; 80,000</option>
                                                    <option>&lt; 90,000</option>
                                                    <option>&lt; 100,000</option>
                                                    <option>&lt; 120,000</option>
                                                    <option>&lt; 150,000</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <select name="body_style" class="css-dropdowns" tabindex="1" >
                                                <option value="">Body Style</option>
                                                <option>Cargo</option>
                                                <option>Compact</option>
                                                <option>Convertible</option>
                                                <option>Coupe</option>
                                                <option>Hatchback</option>
                                                <option>Minivan</option>
                                                <option>Sedan</option>
                                                <option>SUV</option>
                                                <option>Truck</option>
                                                <option>Van</option>
                                                <option>Wagon</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="min-price select-dropdown">
                                            <div class="my-dropdown min-price-dropdown min-dropdown">
                                                <select name="min-mileage" class="css-dropdowns" tabindex="1" >
                                                    <option value="">Min Mileage</option>
                                                    <option>0</option>
                                                    <option>&lt; 10,000</option>
                                                    <option>&lt; 20,000</option>
                                                    <option>&lt; 30,000</option>
                                                    <option>&lt; 40,000</option>
                                                    <option>&lt; 50,000</option>
                                                    <option>&lt; 60,000</option>
                                                    <option>&lt; 70,000</option>
                                                    <option>&lt; 80,000</option>
                                                    <option>&lt; 90,000</option>
                                                    <option>&lt; 100,000</option>
                                                    <option>&lt; 120,000</option>
                                                    <option>&lt; 150,000</option>
                                                </select>
                                            </div>
                                            <span class="my-dropdown">to</span>
                                            <div class="my-dropdown max-price-dropdown min-dropdown">
                                                <select name="max-mileage" class="css-dropdowns" tabindex="1" >
                                                    <option value="">Max Mileage</option>
                                                    <option>0</option>
                                                    <option>&lt; 10,000</option>
                                                    <option>&lt; 20,000</option>
                                                    <option>&lt; 30,000</option>
                                                    <option>&lt; 40,000</option>
                                                    <option>&lt; 50,000</option>
                                                    <option>&lt; 60,000</option>
                                                    <option>&lt; 70,000</option>
                                                    <option>&lt; 80,000</option>
                                                    <option>&lt; 90,000</option>
                                                    <option>&lt; 100,000</option>
                                                    <option>&lt; 120,000</option>
                                                    <option>&lt; 150,000</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <select name="model" class="css-dropdowns" tabindex="1" >
                                                <option value="">Model</option>
                                                <option>Lorem</option>
                                                <option>ipsum</option>
                                                <option>dolor</option>
                                                <option>sit</option>
                                                <option>amet</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <select name="transmission" class="css-dropdowns" tabindex="1" >
                                                <option value="">Transmission</option>
                                                <option>Automatic</option>
                                                <option>Manual</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="select-wrapper clearfix">
                                    <div class="col-md-6">
                                        <div class="my-dropdown make-dropdown">
                                            <select name="make" class="css-dropdowns" tabindex="1" >
                                                <option value="">Make</option>
                                                <option>Lorem</option>
                                                <option>ipsum</option>
                                                <option>dolor</option>
                                                <option>sit</option>
                                                <option>amet</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="my-dropdown">
                                            <input class="full-width" type="search" value="" placeholder="Refine with keywords">
                                        </div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="select-wrapper clearfix">
                                    <div class="form-element clearfix">
                                        <input type="checkbox" id="check">
                                        <label for="check">Certified</label>
                                    </div>
                                    <div class="form-element">
                                        <input type="checkbox" id="check2">
                                        <label for="check2">CARFAX&reg; Verified</label>
                                    </div>
                                    <div class="form-element">
                                        <input type="checkbox" id="check3">
                                        <label for="check3">Brand New</label>
                                    </div>
                                    <div class="form-element">
                                        <input type="submit" value="Find My New Vehicle" class="find_new_vehicle pull-right md-button">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!--invetory ends--> 
                </div>
                
                <div class="recent-vehicles-wrap margin-top-30 sm-padding-left-none">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-14 recent-vehicles padding-left-none">
                            <h5 class="margin-top-none" style="font-size: 16px;">Our Vehicles Promotion</h5>
                            <p>All vehicle promotin in holiday khmer new year start from today until 30-Dec-2015</p>
                            <div class="arrow3 clearfix margin-top-15 xs-margin-bottom-25" id="slideControls3"><span class="prev-btn"></span><span class="next-btn"></span></div>
                        </div>
                        <div class="col-md-8 col-sm-6 padding-right-none xs-padding-left-none">
                            <div class="carasouel-slider3">
                            	<?php 
                            	foreach ($this->vehicle as $rs_vehicle){?>
                                <div class="slide">
                                    <div class="car-block">
                                        <div class="img-flex"> <a href="<?php echo $this->baseUrl();?>/index/vehicle/id/<?php echo $rs_vehicle['id']?>"><span class="align-center"><i class="fa fa-3x fa-plus-square-o"></i></span></a> 
                                        <img style="max-height: 90px;" src="<?php echo $this->baseUrl();?>/images/vehicle/<?php echo $rs_vehicle['img_seat']?>" alt="" class="img-responsive"> </div>
                                        <div class="car-block-bottom" > 
                                       <!--  <div style="text-align: center;" >class before -->
                                            <h6><strong><?php  $rs_vehicle["make"]." ".$rs_vehicle["model"];?></strong></h6>
                                            <h6><?php echo $rs_vehicle["reffer"]?></h6>
                                            <h5 style="font-size: 12px;"><?php echo $rs_vehicle["frame_no"]?></h5>
                                            <h5><?php echo (Int)$rs_vehicle["discount"]?>%off</h5>
                                            <a href="#">Booking Now</a>
                                            <button>Booking Now</button>
                                        </div>
                                    </div>
                                </div>
                                <?php }?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Footer Map -->
                <div class="car-rate-block clearfix margin-top-30 padding-bottom-40">
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12 xs-margin-bottom-40 sm-margin-bottom-none padding-left-none scroll_effect bounceInLeft">
                        <div class="small-block clearfix">
                            <h4 class="margin-bottom-25 margin-top-none">Financing.</h4>
                            <a href="#"><span class="align-center"><i class="fa fa-tag fa-7x"></i></span></a> </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12 xs-margin-bottom-40 sm-margin-bottom-none scroll_effect bounceInLeft" data-wow-delay=".2s">
                        <div class="small-block clearfix">
                            <h4 class="margin-bottom-25 margin-top-none">Warranty.</h4>
                            <a href="#"><span class="align-center"><i class="fa fa-cogs fa-7x"></i></span></a> </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 padding-left-none padding-right-none hours_operation">
                        <div class="small-block clearfix">
                            <h4 class="margin-bottom-25 margin-top-none">What are our Hours of Operation?</h4>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 xs-margin-bottom-40 sm-margin-bottom-40 md-margin-bottom-none scroll_effect bounceInUp" data-wow-delay=".4s">
                                    <table class="table table-bordered no-border font-13px margin-bottom-none">
                                        <thead>
                                            <tr>
                                                <td colspan="2"><strong>Sales Department</strong></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Mon:</td>
                                                <td>8:00am - 5:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Tue:</td>
                                                <td>8:00am - 9:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Wed:</td>
                                                <td>8:00am - 5:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Thu:</td>
                                                <td>8:00am - 9:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Fri:</td>
                                                <td>8:00am - 6:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Sat:</td>
                                                <td>9:00am - 5:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Sun:</td>
                                                <td>Closed</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 xs-margin-bottom-40 sm-margin-bottom-none scroll_effect bounceInUp" data-wow-delay=".4s">
                                    <table class="table table-bordered no-border font-13px margin-bottom-none">
                                        <thead>
                                            <tr>
                                                <td colspan="2"><strong>Service Department</strong></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Mon:</td>
                                                <td>8:00am - 5:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Tue:</td>
                                                <td>8:00am - 9:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Wed:</td>
                                                <td>8:00am - 5:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Thu:</td>
                                                <td>8:00am - 9:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Fri:</td>
                                                <td>8:00am - 6:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Sat:</td>
                                                <td>9:00am - 5:00pm</td>
                                            </tr>
                                            <tr>
                                                <td>Sun:</td>
                                                <td>Closed</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12 xs-margin-bottom-40 sm-margin-bottom-none scroll_effect bounceInRight" data-wow-delay=".2s">
                        <div class="small-block clearfix">
                            <h4 class="margin-bottom-25 margin-top-none">About Us.</h4>
                            <a href="#"><span class="align-center"><i class="fa fa-users fa-7x"></i></span></a> </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12 xs-margin-bottom-40 sm-margin-bottom-none padding-right-none scroll_effect bounceInRight">
                        <div class="small-block clearfix">
                            <h4 class="margin-bottom-25 margin-top-none">Find Us.</h4>
                            <a href="#"><span class="align-center"><i class="fa fa-map-marker fa-7x"></i></span></a> </div>
                    </div>
                </div>
            </section>
            <!--welcome-wrap ends-->
            
            <div class="row parallax_parent margin-top-30">
                <div class="parallax_scroll clearfix" data-velocity="-.5" data-offset="-300" data-no-repeat="true" data-image="http://demo.themesuite.com/automotive/images/parallax2.jpg">
                    <div class="overlay">
                        <div class="container">
                            
                            <div class="row">
                                
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 padding-left-none margin-vertical-60">
                                    <i class="fa fa-car"></i>
                                    
                                    <span class="animate_number margin-vertical-15">
                                        <span class="number">2,000</span>
                                    </span>
                                    
                                    Cars Sold
                                </div>
                                
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-vertical-60">
                                    <i class="fa fa-money"></i>
                                    
                                    <span class="animate_number margin-vertical-15">
                                        $<span class="number">750,000</span>
                                    </span>
                                    
                                    Amount Sold
                                </div>
                                
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-vertical-60">
                                    <i class="fa fa-users"></i>
                                    
                                    <span class="animate_number margin-vertical-15">
                                        <span class="number">100</span>%
                                    </span>
                                    
                                    Customer Satisfaction
                                </div>
                                
                                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 padding-right-none margin-vertical-60">
                                    <i class="fa fa-tint"></i>
                                    
                                    <span class="animate_number margin-vertical-15">
                                        <span class="number">3,600</span>
                                    </span>
                                    
                                    Oil Changes
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
$( document ).ready(function() {
	//document.getElementsByClassName('bx-loading').remove();
});
  </script>
