<?php 
	$db = new Application_Model_DbTable_DbGlobal();
	$facebook = $db->getParameter('facebook');
	$twitter = $db->getParameter('twitter');
	$skype =$db->getParameter('skype');
	$link_in=$db->getParameter('link_in');
	$youtube=$db->getParameter('youtube');
	$google_plus=$db->getParameter('google_plus');
	$instangram=$db->getParameter('instantgram');
	$email = $db->getParameter('email');
	$office_no = $db->getParameter('Office_Phone');
	$phone = $db->getParameter('tel_cambodian');
	$address = $db->getParameter('address_footer');
	$copy_right=$db->getParameter('copyright_footer');
	
	$customer_session  = new Zend_Session_Namespace('customer');
	$user_name = $customer_session->customer_name;
	$verify_acc = $customer_session->verify_acc;
	$verify_address=$customer_session->verify_address;
	$user_mail = $customer_session->cus_email;
	
	$dbpartner = new Other_Model_DbTable_DbPartner();
	$partner = $dbpartner->getAllPartnerToFooter();
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Footer -->
<footer id="footer">
     <div class="container">
            <!-- introduce-box -->
            <div id="introduce-box" class="row">
                <div class="col-md-3">
                    <div id="address-box">
                    	 <div class="introduce-title">Contact</div>
                       <!-- <a href="#"><img src="<?php echo $this->baseUrl()?>/assets/images/aplush_logo.png" alt="logo" /></a>-->
                        <div id="address-list">
                            <div class="tit-name">Address:</div>
                            <div class="tit-contain"><?php echo $address['value'];?></div>
                            <div class="tit-name">Office:</div>
                            <div class="tit-contain"><?php echo $office_no['value'];?></div>
                            <div class="tit-name">Phone:</div>
                            <div class="tit-contain"><?php echo $phone['value'];?></div>
                            <div class="tit-name">Email:</div>
                            <div class="tit-contain"><?php echo $email['value'];?></div>
                            <div></div>
                        </div>
                    </div> 
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="introduce-title">My Account</div>
                            <ul id = "introduce-Account" class="introduce-list">
                                <li><a href="<?php echo $this->baseUrl().'/index/order';?>">My Order</a></li>
                               
                                <li><a href="<?php  if (!empty($customer_session->customer_name)){  echo $this->baseUrl().'/index/profile';} else{echo $this->baseUrl().'/index/register';}?>">My Personal In</a></li>
   								<?php if (empty($customer_session->customer_name)){?>
   								<li><a href="<?php echo $this->baseUrl().'/index/register';?>">Login & Register</a></li>
                           		<?php }else{?>
                           		<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'customerlogout')); ?>">Logout</a></li>
                           		<?php }?>
                            </ul>
                        </div>
                        <div class="col-sm-8">
                            <div class="introduce-title">Facebook Fan</div>
                            <div class="fb-page" data-href="<?php echo $facebook['value'];?>" data-tabs="timeline" data-width="300" data-height="151" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="<?php echo $facebook['value'];?>"><a href="<?php echo $facebook['value'];?>">Facebook</a></blockquote></div></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div id="contact-box">
                        <div class="introduce-title">Let's Socialize</div>
                        <div class="social-link">
                            <a href="<?php echo $facebook['value'];?>" target="blank"><i class="fa fa-facebook"></i></a>
                            <a href="<?php echo $youtube['value'];?>" target="blank"><i class="fa fa-youtube"></i></a>
                            <a href="<?php echo $skype['value'];?>" target="blank"><i class="fa fa-skype"></i></a>
                            <a href="<?php echo $twitter['value'];?>" target="blank"><i class="fa fa-twitter"></i></a>
                            <a href="<?php echo $google_plus['value'];?>" target="blank"><i class="fa fa-google-plus"></i></a>
                        </div>
                    </div>
                    
                </div>
            </div><!-- /#introduce-box -->
        
            <!-- #trademark-box -->
            <?php  if (!empty($partner)){?>
            <div id="trademark-box" class="row">
                <div class="col-sm-12">
                    <ul id="trademark-list">
                        <li id="payment-methods">OUR CUSTOMER</li>
                        <?php if (!empty($partner)) foreach ($partner as $row){?>
                        <li>
                        	<img title="<?php echo $row['title'];?>" src="<?php echo $this->baseUrl()?>/images/partner/<?php echo $row['image_partner'];?>"  alt="<?php echo $row['title'] ?>"/>
                        </li>
                        <?php }?>
                    </ul> 
                </div>
            </div> <!-- /#trademark-box -->
            <?php }?>
           <div class="col-sm-2"></div><div class="col-sm-8"><div class="triangle"></div></div><div class="col-sm-2"></div>
            <div id="footer-menu-box">
                <div class="col-sm-12">
                    <ul class="footer-menu-list">
                        <li><a href="<?php echo $this->baseUrl().'/index/termcondition'?>" >Terms & Conditions</a></li>
                        <li><a href="<?php echo $this->baseUrl().'/index/policy'?>" >Policy</a></li>
                        <li><a href="<?php echo $this->baseUrl().'/index/faq-us'?>" >FAQ</a></li>
                        <li><a href="<?php echo $this->baseUrl().'/index/delivery'?>" >Delivery Information</a></li>
                        <li><a href="<?php echo $this->baseUrl().'/index/about-us'?>" >About Us</a></li>
                        <li><a href="<?php echo $this->baseUrl().'/index/contact-us'?>" >Contact</a></li>
                    </ul>
                </div>
                 
            </div><!-- /#footer-menu-box -->
        </div> 
</footer>

<div class="footer-copyright">
	<div class="container">
               <div class="col-sm-12"> <p class="text-center"><?php echo $copy_right['value'];?> Developed by <strong><a class="develop" href="http://www.cam-app.com/" alt="Cam APP Technology" title="Cam APP Technology">Cam APP Technology</a></strong></p></div>
	</div>
</div>
<a href="#" class="scroll_top" title="Scroll to Top" style="display: inline;">Scroll</a>
<!-- Script-->
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/jquery/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/select2/js/select2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/jquery.bxslider/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/owl.carousel/owl.carousel.min.js"></script>
<!--<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/jquery.countdown/jquery.countdown.min.js"></script>-->
<!-- COUNTDOWN -->
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/countdown/jquery.plugin.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/countdown/jquery.countdown.js"></script>
<!-- ./COUNTDOWN -->
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/js/jquery.actual.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/js/theme-script.js"></script>


<!-- Script-->
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/jquery.elevatezoom.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/lib/fancyBox/jquery.fancybox.js"></script>

