<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$request=Zend_Controller_Front::getInstance()->getRequest();
echo $this->headTitle($tr->translate("PRODUCTS"));
 $status = $request->getParam('search_status');
 if(empty($status)) $status=-1;
 $make=$request->getParam('make');
 $model=$request->getParam('model');
 $submodel=$request->getParam('submodel');
 $url_copy = $this->url(array('module'=>'food','controller'=>'index','action'=>'copy',
 ));
 $formList = new Application_Form_Frmtable();
 $frm =  $this->form_search;
?>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");

var make_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_make));?> );
dojo.ready(function(){
new dijit.form.FilteringSelect({
    store: make_store,
    autoComplete: true,                        
   // required: true,
    required: false,
    id: "make",
    name: "make",    
    placeHolder:"Selected category",       
    class: 'fullside',   
    value:'<?php echo $make; ?>',       
    onChange: function() {  
    		make_id=dijit.byId('make').get('value');
    		//alert(make_id);
    		//getallModel(make_id);
    }
}, "make");	

	}); 

</script>
<style>
	.btn-action{background: rgb(168, 18, 246) none repeat scroll 0% 0%;padding: 3px 10px;border-radius: 5px;}
	.btn-action b{color: white;padding: 0px 4px;}
</style>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'food','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
	  <tr> 
		   <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $request->getParam('adv_search');?>" placeholder="<?php echo $this->translate("Search");?>" type="text" ></td>
		   <td><input id="make" /></td>
		   <td>
		         <td> <?php echo $frm->getElement("status_search");?></td>
		   </td>
		   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	 	<td><?php echo $formList->showCopyBuntton($url_copy);?></td>
   	  </tr>
   </table>
   <?php echo $this->list;?>
</form>

<script>
function copyRecord(url) {
	 var cbs = $("input:checkbox"); //find all checkboxes
	 var nbCbs = cbs.size(); //the number of checkboxes
	 var checked = $("input[@type=checkbox]:checked"); //find all checked checkboxes + radio buttons
	 var nbChecked = checked.size();
	 if(nbChecked < 1) {
	  alert("Please select record to copy!");
	 } else {
	  /*var answer = confirm("Are you sure you want to delete it?")
	     if (answer){*/
	   id = new Array();
	   var i = 0;
	   checked.each(function() {
	    id[i] = $(this).val();
	    i++;
	   });
	   window.location.href = url+'/id/'+id;
	     /*} else {
	      alert("Sorrty can't delete it!");
	     }*/
	 }
	}
</script>