<?php 
     $url_save = $this->url(array('module'=>'service','controller'=>'index','action'=>'edit'));
     $close = $this->url(array('module'=>'service','controller'=>'index','action'=>'index'));
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $row=$this->row;
     $status_view=$this->status_view;
    // print_r($status_view);exit();
?>
<title><?php echo $this->tr->translate("SERVICE")?></title>
<form id="add_province" action="<?php echo $url_save;?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong>Add Category</strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td>Name In Khmer</td>
										<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="name_kh" name="name_kh" value="<?php echo $row['title']?>" type="text" required="required"></td>
									</tr>
									<tr>
										<td>Status</td>
										<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
											<?php foreach ($status_view as $rs){?>
												<option value="<?php echo $rs['key_code'];?>" label="Active" selected="selected"><?php echo $rs['name_en'];?></option>
											 <?php }?>
											</select>
										</td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="submit" value="save_close" name="save_close" label="Save&Close" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form> 