<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Customer List"));
?>	
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dijit.form.FilteringSelect");  
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.DateTextBox");
//require(["dojo/parser", "dijit/form/TimeTextBox"]);
dojo.ready(function(){
	dijit.byId('start_date').attr('value','<?php echo $this->search["start_date"];?>');
	dijit.byId('end_date').attr('value','<?php echo $this->search["end_date"];?>');
});
</script>


<?php //$frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table>
		<tr>
			<td><input type="text" dojoType="dijit.form.TextBox" name="title" id="title" placeholder="Advand search" value="<?php $this->search["title"];?>" /></td>
			<td>
		   		<input dojoType="dijit.form.DateTextBox" name="start_date" id="start_date" class="fullside" >
	    	</td>
	    	<td>
		   		<input dojoType="dijit.form.DateTextBox" name="end_date" id="end_date" class="fullside" >
	    	</td>
			<td></td>
			<td>
				<select name="status_search" id="status_search" dojoType="dijit.form.FilteringSelect">
		 			<option value="-1">Status</option>
		 			<option value="1">Active</option>
		 			<option value="0">Deactive</option>
		 		</select>
			</td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
 		
 		
 		
 		
  <?php //echo $frm->getElement('status_search');?>
    
<?php echo $this->list;?>
</form>