<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Supplier List"));
?>	<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dijit.form.FilteringSelect");  
dojo.require("dijit.form.TextBox");
//require(["dojo/parser", "dijit/form/TimeTextBox"]);
</script>
<?php //$frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'supplier','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
 		<input type="text" dojoType="dijit.form.TextBox" name="title" id="title" placeholder="Advand search" value="<?php echo $this->row_search['title']?>" />
 		<select name="company" id="company" dojoType="dijit.form.FilteringSelect">
 			<option value="-1">Company</option>
 			<?php if (!empty($this->company)) foreach($this->company as $row){?>
 			<option value="<?php echo $row['id'];?>"><?php echo $row['title'];?></option>
 			<?php }?>
 		</select>
 		<select name="status_search" id="status_search" dojoType="dijit.form.FilteringSelect">
 			<option value="-1">Status All</option>
 			<option value="1" <?php if($this->row_search['status_search']==1) echo 'selected="selected"';?> >Active</option>
 			<option value="0" <?php if($this->row_search['status_search']==0) echo 'selected="selected"';?> >Deactive</option>
 		</select>
  <?php //echo $frm->getElement("title");?>
  <?php //echo $frm->getElement('status_search');?>
    <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
<?php echo $this->list;?>
</form>