<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Supplier List"));
	$frm =  $this->form_search;
?>	<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dijit.form.FilteringSelect");  
dojo.require("dijit.form.TextBox");
//require(["dojo/parser", "dijit/form/TimeTextBox"]);
</script>
<?php //$frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'supplier','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
 	<table width="60%">
 	  <tr>
 	    <td>
 		<input type="text" dojoType="dijit.form.TextBox" name="title" id="title" class="fulside" placeholder="Advand search" value="<?php echo $this->row_search['title']?>" />
 		</td>
 		<td>
 		<select name="company" id="company" dojoType="dijit.form.FilteringSelect" class="fulside">
 			<option value=""><?php echo $tr->translate("COMPANY_NAME");?></option>
 			<?php if (!empty($this->company)) foreach($this->company as $row){?>
 			<option value="<?php echo $row['id'];?>" <?php if($this->row_search['company']==$row['id']) echo 'selected="selected"';?> ><?php echo $row['name'];?></option>
 			<?php }?>
 		</select>
 		</td>
 		<td>
 		 <?php echo $frm->getElement("status_search");?>
 		</td> 
       <td>
       <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        </td>
      </table>
    
</form>
<?php echo $this->list;?>