<title>All Gategory Food</title>
<?php 
     $frm=$this->form_search;
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
tr.normal td, tr.alternate td {
    border: 1px solid #0C0C0C;
    line-height: 14px;
    padding: 0px 2px 0px 2px;
    font-size: 11px;
}
</style>
 <meta charset="utf-8">
 <form  action="<?php echo $this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-food')); ?>" dojoType="dijit.form.Form" method="post">
					   <table style="width:50%">
						  <tr> 
						       <td> <?php echo $frm->getElement("adv_search");?></td>
							   <td> <?php echo $frm->getElement("cat_food");?></td>
							   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					   	  </tr>
					   	  <tr>
					   	        <td> <?php //echo $frm->getElement("start_date");?></td>
							   <td> <?php //echo $frm->getElement("end_date");?></td>
							   
					   	  </tr>
					   </table>
 </form>
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
<div id="divPrint"  >
<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
										
<tr>
	    <td width="28%" align="left">
		   <!-- <img style="width:70%;" src="/ahs/trunk/public/images/logo.png"><br /><br > -->
		</td>
		<td align="center" width="44%">
			<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​  អតិថិជន</strong><br />
        <span style="font-weight: bold;font-size: 11px;">From &nbsp;<?php echo date('Y-m-d');?> &nbsp;To&nbsp; 04-Aug-2016</span><br /><br />
		</td>
		<td width="28%" align="right">
		</td>
	</tr>
<tr>
	<td colspan="3">
    <?php $food=new Report_Model_DbTable_DbFoodGategory();$cat_blank='';?>
	<?php if(!empty($this->gategory)) foreach ($this->gategory As $gategory){?>
	 <?php if($gategory['id']!=$cat_blank){?>
	            <br>
	            <table style="width:100%;">
	                <tr>
	                	<td  style="background-color:#CCCCCC;padding-left: 10px;s" >
	                	    <style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
							</style>
	                		<strong style="font-weight:bold;font-family: Arial Black;color:#3F51B5; font-size: 11px;font-family:'Khmer MEF2';">Category Type( ប្រភេទអាហារ):<?php echo $gategory['name_kh'];?>
	                	 </strong></td>
	                </tr>
	            </table>
	    
		<table    border="1px solide #000;" id="exportExcel" width="100%" style=" font-size: 11px;">
			<tr style="font-size:10px; height: 18px;"​ >
				<th>&nbsp;No.</th>
				<th>&nbsp;Food Code</th>
				<th>&nbsp;Food Namer</th>
				<th>&nbsp;Price</th>
				<th>&nbsp;Status</th>
			</tr>
			<?php foreach ($food->getFoodByCategoryId($gategory['id']) As $num =>$rs){ $num=$num+1;?>
			<?php if($gategory['id']==$rs['cat_id']){?>
			
			<?php if($rs["status"]==1){
			          $status="Active";
			       }else{
			       	  $status="Deactive";
			       }
				?>
			<tr class="normal"  style="font-size:10px; height: 18px;"​ >
				<td class="items-no">&nbsp;<?php echo $num;?></td>
				<td class="items" >&nbsp;<a href="<?php echo $this->baseUrl();?>/report/index/rpt-item-food/id/<?php echo $rs["id"]?>"><?php echo $rs["food_code"]?></a></td>
				<td class="items" >&nbsp;<?php echo $rs["name_kh"]?></td>
				<td class="items">&nbsp;<?php echo $rs["price"]?></td>
				<td class="items">&nbsp;<?php echo $status?></td>
			</tr>
			<?php }else{$cat_blank=$rs['cat_id'];} }?>
		</table>
		
	<?php } $cat_blank=1;}?>
  </td>
  </tr>
 </table>
</div>
</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
</script>