<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     //$this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
.absolute{ position: absolute !important; top: 210px !important;}
.tbl_first{width:20% !important;}
.tbl_second{width:60% !important;}
</style>

<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">

<style>
.bg{ background:#eeeeee; border:1px solid #000;}

select{ width:100%;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .display_form-add{display:none;}
td .td-left{text-align:right !important;}
</style>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.html");
dojo.require("dojo.parser");
dojo.require("dojo.NodeList-manipulate");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);

dojo.ready(function(){
	addRowAjax();
});
</script>
<div id="divPrint" style="width: 100%;">
<style>
.bg{ background:#eeeeee; border:1px solid #000;}

select{ width:100%;}
table.collape {
    border-collapse: collapse;
    margin: 0px;
    padding: 0px;
    width: 100%;}
    th.tdheader {
    background: url("../images/tbheader-bg1.jpg") repeat-x scroll center top #F1F1F1;
    border: 1px solid #CCCCCC;
    color: #333333;
    /* font-family: Arial,Helvetica,sans-serif; */
    font-family: 'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif;
    font-size: 12px;
    font-weight: bold;
    line-height: 30px;
    padding: 2px 2px 2px 2px;
    text-align: center;
    cursor: pointer;
}
tr.normal td, tr.alternate td {
    border: 1px solid #DDDDDD;
    line-height: 14px;
    padding: 0px 2px 0px 2px;
    font-size: 11px;
}
td.items-no {
    padding: 5px !important;
    text-align: center;
}
</style>
<table style="background:#fff;width:90%; margin: 0 auto;width: 70%;">
	<tr>
		<td align="center" >
			<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​  កម្មង់ម្ហូប</strong><br />
		</td>
		
	</tr>
</table>

<table class="collape tablesorter" id="exportExcel" width="100%" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;">
	<tr style="background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;">
		<th class="tdheader header"><?php echo $tr->translate("NO");?></th>
		<th class="tdheader header"><?php echo $tr->translate("ORDER_NO");?></th>
		<th class="tdheader header"><?php echo $tr->translate("MERGE_CODE");?></th>
		<th class="tdheader header"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
		<th class="tdheader header"><?php echo $tr->translate("PHONE");?></th>
		<th class="tdheader header"><?php echo $tr->translate("EMAIL");?></th>
		<th class="tdheader header"><?php echo $tr->translate("CEREMONY_DATE");?></th>
		<th class="tdheader header"><?php echo $tr->translate("CEREMONY_ADDRESS");?></th>
		<th class="tdheader header"><?php echo $tr->translate("TOTAL");?></th>
	</tr>
	<?php foreach ($this->rows as $key=>$rs){ $num = $key+1;?>
	<tr class="normal">
		<td class="items-no"><?php echo $num;?></td>
		<td class="items"><a href="<?php echo $this->baseUrl();?>/report/index/vieworder/id/<?php echo $rs["id"]?>"><?php echo $rs["order_code"]?></a></td>
		<td class="items"><a href="<?php echo $this->baseUrl();?>/report/index/viewmerge/id/<?php //echo $rs["merge_id"]?>"><?php //echo $rs["merge_id"]?></a></td>
		<td class="items"><a href="<?php echo $this->baseUrl();?>/report/index/vieworder/id/<?php echo $rs["id"]?>"><?php echo $rs["first_name"]?></a></td>
		<td class="items"><a href="<?php echo $this->baseUrl();?>/report/index/vieworder/id/<?php echo $rs["id"]?>"><?php echo $rs["phone"]?></a></td>
		<td class="items"><?php echo $rs["email"]?></td>
		<td class="items"><?php echo $rs["ceremony_date"]?></td>
		<td class="items"><?php echo $rs["address_1"]?></td>
		<td class="items"><?php echo $rs["total_pay"]?></td>
	</tr>
	<?php }?>
</table>
</div>
</div>