<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CUSTOMER'));
?>	
<?php  $frm = $this->frm_client;?>
<style>
fieldset{border: 1px solid #ccc; }
fieldset table td input ,fieldset table td select{color: #000 !important; }
tr .display_branch{display:none;}
</style>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);


dojo.ready(function(){
	$('#old_cu').hide();
// 	try{	
// 		Showbranch();
// 	}catch(e){
// 		alert(e);
// 	}
	var province_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->province));?> );
	new dijit.form.FilteringSelect({
	    store: province_store,
	    autoComplete: true,                        
	    required: true,
	    placeHolder:"Select province...",
	    id: "province",
	    name: "province",           
	    class: 'fullside',            
	    onChange: function() { 
	    	getAllDistrict();      
	    } 
	}, "province");
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "district",
	    name: "district",         
	    class: 'fullside',  
	    placeHolder:"Selected district...",          
	    onChange: function() {  
		    distric_id = dijit.byId('district').get('value');
		    if(distric_id == -1){
			   
	    		dijit.byId("pop_district").show();
		    }
	    }
	}, "district");

});
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else{
				return false;
			}
</script>
			<table style=" width: 100%">
							<tr>
								<td valign="top" width="34%" style="white-space: nowrap;">
										<fieldset>
											<legend align="center"><strong><?php echo $tr->translate("ADD_CUSTOMER");?>​</strong></legend>
											<table style="margin: 0 auto;" cellspacing="10">
												<tr>
													<td>អតិថិជនចាស់ :</td>
													<td><input type="checkbox" name="is_new_cu" id="is_new_cu" value="1" onClick="isNewCustomer()" ></td>
												</tr>
													<tr>
													   <td><?php echo $tr->translate("CUSTOMER_NAME")?>*</td>
													   <td>
													   		<span id="new_cu">
													   			<input type="text" dojoType="dijit.form.TextBox" name="first_name"  id="first_name" value="" class="fullside" required="required">
													   		</span>
													   		<span id="old_cu">
													   			<select dojoType='dijit.form.FilteringSelect' id="cu_id" name="cu_id" onChange="getCustomer()" class="fullside" required="false">
														   			<?php foreach ($this->cu_name as $rs){?>
														   			<option value="<?php echo $rs["id"]?>"><?php echo $rs["first_name"]?></option>
														   			<?php }?>
													   			</select>
													   		</span>
													   		
													   	</td>
													   <td><?php echo $tr->translate("CUSTOMER_ID")?></td>
													   <td><input type="text" dojoType="dijit.form.TextBox" readonly="readonly" name="client_no"  id="client_no" value="<?php echo $this->cus_no;?>" class="fullside"></td>
													</tr>
													<tr>
													   <td><?php echo $tr->translate("SEX")?></td>
													   <td><select dojoType='dijit.form.FilteringSelect' id="title" name="title" class="fullside">
													   			<option value="1"><?php echo $tr->translate("MALE")?></option>
													   			<option value="2"><?php echo $tr->translate("FEMALE")?></option>
													   		</select>
													   	</td>
													   <td><?php echo $tr->translate("Tel")?>*</td>
													   <td><input type="text" dojoType="dijit.form.TextBox" required="required" name="phone"  id="phone" value="" class="fullside"></td>
													</tr>
													<tr>
														<td><?php echo $tr->translate("EMAIL")?></td>
											   			<td><input type="text" dojoType="dijit.form.TextBox" value="" required="required"  id="email" name="email" class="fullside" /></td>
											   			<td><?php echo $tr->translate("ADDRESS")?></td>
											   			<td><input type="text" dojoType="dijit.form.TextBox" value="" required="required"  id="address" name="address" class="fullside" /></td>
													</tr>
													
											</table>
										</fieldset>
								</td>
							</tr>
							<tr>
								<td width="100%" align="top">
									<fieldset><legend align="center"><strong><?php echo $tr->translate("CEREMONY_INFO")?></strong></legend>
									   <table style="padding-left:10px;" cellspacing="10">
											<tr>
												<td><?php echo $tr->translate("CEREMONY_DATE")?></td>
												<td><input type="text" dojoType="dijit.form.DateTextBox" value="<?php echo date('Y-m-d');?>"  id="ceremony_date" name="ceremony_date" class="fullside" /></td>
												<td><?php echo $tr->translate("METTING")?></td>
												<td><select dojoType='dijit.form.FilteringSelect' id="meeting" name="meeting" class="fullside">
													   	<option value="0">Not yet Meeting</option>
													   	<option value="1">Has Meeting</option>
													 </select>
												</td>
												<td><?php echo $tr->translate("STATUS")?></td>
												<td><select dojoType='dijit.form.FilteringSelect' id="status" name="status" onchange="Showbranch();" class="fullside">
													   <option value="1">Active</option>
													   <option value="0">Deactive</option>
													 </select>
												</td>
											</tr>
											
											<tr>
												<td><?php echo $tr->translate("ADDRESS_ONE")?></td>
												<td colspan="3"><input type="text" dojoType="dijit.form.TextBox" required="required" name="ceremony_add1"  id="ceremony_add1" value="" class="fullside"></td>
											</tr>
											<tr>
												<td><?php echo $tr->translate("ADDRESS_TWO")?></td>
												<td colspan="3"><input type="text" dojoType="dijit.form.TextBox"   name="ceremony_add2"  id="ceremony_add2" value="" class="fullside"></td>
											</tr>
											<tr>
												<td><?php echo $tr->translate("ADDRESS_THREE")?></td>
												<td colspan="3"><input type="text" dojoType="dijit.form.TextBox"   name="ceremony_add3"  id="ceremony_add3" value="" class="fullside"></td>
											</tr>
										</table>
									</fieldset>
								</td>
							</tr>
							 <tr align="center">
								<td valign="top">
										<input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
											iconClass="dijitIconClear" /> 
										<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
											iconClass="dijitEditorIcon dijitEditorIconSave" /> 
										<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" style="color:#000;" dojoType="dijit.form.Button" name="save_new"
											iconClass="dijitEditorIcon dijitEditorIconSave"/>
								</td>
							</tr>
							<tr style="background: #711A7B">
									<td colspan="3" align="center">
										
								     </td>
							</tr>
					</table>	
</form>


<script type="text/javascript">  

var url_addDistrict = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district')); ?>';
function addDistrict(){
	if(dijit.byId('frm_district').validate()){
		dojo.xhrPost({
			url:url_addDistrict,
			form: dojo.byId("frm_district"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('district_name').get('value')
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, Itemmake, data);
				dijit.byId('frm_district').reset();
				dijit.byId("pop_district").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}



var district_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_district = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'get-district')); ?>';
	function getAllDistrict(){
		province_id = dijit.byId('province').get('value');
		//alert(province_id);
			dojo.xhrPost({
				url:url_district,
				content:{
					'province_id':province_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					dijit.byId('district').reset('value');
					district_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('district').set('store',district_store);   

				},
				error: function(err) {
					alert(err);
				}
			});
	}

function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}
function Showbranch(){
	 type_cus = dijit.byId('cus_type').get('value');
	 var a = document.getElementById("branch");
					//alert(data);
					if(type_cus==1){
						//alert(1);
						a.classList.add("display_branch");
						
					}else{
						a.classList.remove("display_branch");
						
					}
}

var url_customer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'get-customer')); ?>';
function getCustomer(){
	id = dijit.byId('cu_id').get('value');
		dojo.xhrPost({
			url: url_customer,
			content:{
				'id':id
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('client_no').attr('value',data.customer_code);
				dijit.byId('title').attr('value',data.title);
				dijit.byId('first_name').attr('value',data.first_name);
				dijit.byId('phone').attr('value',data.phone);
				dijit.byId('email').attr('value',data.email);
				dijit.byId('address').attr('value',data.address);
			},
			error: function(err) {
				alert(err);
			}
		});
}

function isNewCustomer(){
	is_new = $('#is_new_cu').val();
	if($('#is_new_cu').is(':checked')){
		//dijit.byId('first_name').attr('required',"required");
		$('#old_cu').show();
		$('#new_cu').hide();
	}else{
		$('#old_cu').hide();
		$('#new_cu').show();
	}
	
}
</script>