<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Customer List"));
	$frm =  $this->form_search;
?>	
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dijit.form.FilteringSelect");  
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.DateTextBox");
//require(["dojo/parser", "dijit/form/TimeTextBox"]);
dojo.ready(function(){
	
});
</script>



 <form  action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
					   <table style="width:80%">
						  <tr> 
							    <td> <?php echo $frm->getElement("title");?></td>
							    <td> <?php echo $frm->getElement("start_date");?></td>
							    <td> <?php echo $frm->getElement("end_date");?></td>
							    <td> <?php echo $frm->getElement("status_search");?></td>
							    
							   <td> <?php //echo $frm->getElement("time");?></td>
							   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					   	  </tr>
					   </table>
 </form>
 		
 		
<?php echo $this->list;?>
